### ISSUE TITLE
1.0 Contribution

### ISSUE THREAD

**Issue by rwatts3** [orionjs/orion#101]
Hi @nicolaslopezj , 

I am trying to contribute to 1.0 either helping or beta testing. When I cloned the 1.0 branch I can't seem to get it working any advice on setup ? 

I cloned the 1.0 example-blog , and cloned the 1.0 packages directory into the example-blog.

**Comment by nicolaslopezj** [comment]
Example blog need to be updated too. Tomorrow I will specify instructions for beta testers

**Comment by rwatts3** [comment]
Very well, 

Thank you for the update.

**Comment by nicolaslopezj** [comment]
In the meantime you can test nicolaslopezj/reactive-templates, the package that orion 1.0 uses to allow developers to override templates
