### ISSUE TITLE
Users Attribute possible Extension to Custom Selections

### ISSUE THREAD

**Issue by rwatts3** [orionjs/orion#102]
I like how the users attribute allows you to select multiple users. 
Is it possible to use this attribute to select multiple values of a different entity. 
For instance if I have an entity of events , I want to attach multiple venues the same way users do. 
Can I do this with the users-attribute , or is there a way to extend the users attribute so that I can pass in my own field to select multiple values on .

**Comment by nicolaslopezj** [comment]
Try with orionjs:relationships

**Comment by rwatts3** [comment]
Will it render the same autoform field as users does. Like the dropdown, and the item with an x next to it ?

**Comment by nicolaslopezj** [comment]
Yes

**Comment by rwatts3** [comment]
Perfect ! 

I will give this a shot thank you.
