### ISSUE TITLE
trying to install - "s is not defined"

### ISSUE THREAD

**Issue by zaklampert** [orionjs/orion#103]
Trying to create a test app to test out your project. I believe I followed the documentation for setup correctly

In a new meteor project I have installed 
```
meteor-platform
orionjs:bootstrap
twbs:bootstrap
fortawesome:fontawesome
```
I run "meteor" and  when I view /admin I get a client console error "Uncaught Reference Error: s is not defined"  in file helpers.coffee:4

When I try to create the first user, the console (client) spits out

```
debug.js:41 Exception from Tracker recompute function:
debug.js:41 Error: No such function: isActiveRoute
    at Blaze.View.lookup (lookup.js:125)
    at Spacebars.call (spacebars-runtime.js:130)
    at Spacebars.mustacheImpl (spacebars-runtime.js:67)
    at Object.Spacebars.mustache (spacebars-runtime.js:71)
    at Template.adminSidebar.HTML.NAV.HTML.DIV.HTML.UL.Blaze.If.HTML.LI.class (base.html:157)
    at Object.Blaze._withCurrentView (view.js:523)
    at Blaze._HTMLJSExpander.def.visitAttribute (view.js:451)
    at HTML.TransformingVisitor.def.visitAttributes (visitors.js:171)
    at Blaze._HTMLJSExpander.def.visitAttributes (view.js:445)
    at Object.Blaze._expandAttributes (view.js:474)
```
Is there more setup required?

**Comment by timfam** [comment]
Just give me a minute to look into this, I suppose coffee file must have come from my PR

**Comment by timfam** [comment]
I can't find a single coffee file in the packages. Hold I will do new install. Btw a new version will be out pretty soon. It will be breaking change from present

**Comment by zaklampert** [comment]
Is there an older version I should try in the meantime? Just wanting to poke around.

**Comment by timfam** [comment]
this is the older version. I am do brand new install give me a few minutes

**Comment by timfam** [comment]
Error is from an external dependant package becuase a route is not yet setup.
```
Uncaught ReferenceError: s is not defined   
//That error is coming from  zimme_iron-router-active.js:59
name = name + 'Active' + s.capitalize(type);
```
We have a example blog distribution you can play around with for now https://github.com/orionjs/example-blog enjoy and give us your feedback we here if you have questions

**Comment by zaklampert** [comment]
Does that mean I just need to create a "/" route?

**Comment by timfam** [comment]
The blog is the best place to start, it is the perfect intro to orionjs

**Comment by zaklampert** [comment]
Great, thanks for your help.

Let's say I'm wanting to start from scratch eventually. Is this something that can be fixed?

**Comment by nicolaslopezj** [comment]
@zaklampert we need more information about this error to get this fixed.
I have never seen this error.

**Comment by zaklampert** [comment]
@nicolaslopezj I was just attempting to create a blank project from scratch. I added the packages as shown. Is there more setup needed? Obviously I will need to create entities, etc, but I got that error just by trying to create the first admin user.

**Comment by rwatts3** [comment]
Like @timfam said I would clone the blog then take out what you don't need.

**Comment by timfam** [comment]
@zaklampert  this version will soon be deprecated. Lets save energy for main release.

**Comment by zaklampert** [comment]
Great, thanks all.

**Comment by kevohagan** [comment]
this error is from zimme:iron-router-active package

its resolved now in the package 

https://github.com/zimme/meteor-iron-router-active/issues/18
