### ISSUE TITLE
Server rendered pages

### ISSUE THREAD

**Issue by vonwao** [orionjs/orion#104]
What's the story of Meteor and Orion around server rendered pages (or routes)?  It looks like, on any page render it will pretty much require downloading the meteor stack including a bunch of packages, and wait for DDP connection to come up.  If someone is browsing a site on their mobile phone on a bad network, I think this would be really slow.  Also server rendered pages could be good for SEO.  Thoughts?

It looks like [meteorhacks/fast-render](https://github.com/meteorhacks/fast-render) or [meteorhacks/meteor-ssr](https://github.com/meteorhacks/meteor-ssr) could help.

(I'm not suggesting this for the admin panel, maybe as an option for public facing pages and routes.  Maybe this should be part of pages or a separate package.)

**Comment by timfam** [comment]
Fast-render is a performance tweak that should become best practice so for the front facing routes yes sure we should use it.

**Comment by mraak** [comment]
This is a must for any serious, commercial website. SEO is hampered a lot if you wait for JS to populate pages.

**Comment by mraak** [comment]
At least to fix the SEO part, this package could help: https://atmospherejs.com/meteor/spiderable

**Comment by nicolaslopezj** [comment]
Orion is compatible with spiderable

**Comment by timfam** [comment]
I think we should add that to example blog

**Comment by nicolaslopezj** [comment]
You only have to add the package, nothing else
