### ISSUE TITLE
Is there a direct path for user create at client side?

### ISSUE THREAD

**Issue by loongmxbt** [orionjs/orion#106]
I've searched `orion/core/users/accounts-templates.js` and cannot find a path such as `/signup`. I can create a user by `/login` and hit the register link, the url doesn't change. So how to directly enter the register path and template?

```
orion.users.configure({
    forbidClientAccountCreation: false,
    defaultPermissions: ['entity.posts.personal']
})
```

**Comment by nicolaslopezj** [comment]
You can use this
```js
Router.path('login', {}, { query: { redirect: Router.current().url } })
```
