### ISSUE TITLE
Blank page after the creation of the administrator

### ISSUE THREAD

**Issue by SICCVI** [orionjs/orion#107]
Hello,

I test Orion following the installation procedure. After creating my first user, I am facing a blank page. Tested on Chrome and Firefox.

[Update] Note: In a first connection with a browser other than the one used to create the admin account, the sign-in page (http://192.168.1.16:3000/admin/change-password) is proposed. But after entering the password, the page freezes. After reactualization the page is blank.

[Update2] : On the admin panel, and before the blank page i must click twice. The first time the button is pressed and nothing else.

Thank you in advance,

**Comment by nicolaslopezj** [comment]
Hi, can you provide the logs?

**Comment by SICCVI** [comment]
Hi Nicolas,

Sorry but where i can find them ?

**Comment by nicolaslopezj** [comment]
In the inspector of your browser

**Comment by SICCVI** [comment]
Log Chrome
--------------------

1) Uncaught ReferenceError: s is not defined

isActive = (type, inverse = false) ->
  name = 'is'
  name = name + 'Not' if inverse
  name = name + 'Active' + s.capitalize type   <-------------helpers.coffee:4

  (view) ->
    unless view instanceof Spacebars.kw
      throw new Error "#{name} options must be key value pair such " +
        "as {{#{name} regex='route/path'}}. You passed: " +
        "#{JSON.stringify view}"

2) Uncaught Error: No such function: isActiveRoute

  } else {
    return function () {
      var isCalledAsFunction = (arguments.length > 0);
      var data = Blaze.getData();
      if (lookupTemplate && ! (data && data[name])) {
        throw new Error("No such template: " + name);
      }
      if (isCalledAsFunction && ! (data && data[name])) {
        throw new Error("No such function: " + name);  <------------------ lookup.js:125
      }

Log firefox
--------------------

"Exception from Tracker recompute function:" meteor.js:888:10
"Error: No such function: isActiveRoute" meteor.js:888:10
"Blaze.View.prototype.lookup/<@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2982:1
Spacebars.call@http://192.168.1.16:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:172:12
Spacebars.mustacheImpl@http://192.168.1.16:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:109:10
Spacebars.dataMustache@http://192.168.1.16:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:141:16
Template.adminConfigPassword</</<.class/<@http://192.168.1.16:3000/packages/orionjs_bootstrap.js?3d2e27ea4f17b6d627eebb8dcfc3852fa8e3a4d2:786:1
Blaze.If/</<@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2626:44
viewAutorun/</<@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1865:16
Template._withTemplateInstanceFunc@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3476:12
viewAutorun/<@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1864:1
Blaze._withCurrentView@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2197:12
viewAutorun@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1863:1
Tracker.Computation.prototype._compute@http://192.168.1.16:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:327:5
Tracker.Computation@http://192.168.1.16:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:243:5
Tracker.autorun@http://192.168.1.16:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:566:11
Blaze.View.prototype.autorun@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1875:14
Blaze.If/<@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2625:1
fireCallbacks@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1941:9
Tracker.nonreactive@http://192.168.1.16:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:593:12
Blaze._fireCallbacks/<@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1938:5
Blaze._withCurrentView@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2197:12
Blaze._fireCallbacks@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1937:3
Blaze._createView@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1955:3
Blaze._expandView@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2080:3
.visitObject@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2108:1
.visit@http://192.168.1.16:3000/packages/htmljs.js?567eb96d5d22631c03d6aca6afa4c42f0d1295f2:118:14
.visitArray@http://192.168.1.16:3000/packages/htmljs.js?567eb96d5d22631c03d6aca6afa4c42f0d1295f2:157:21
.visit@http://192.168.1.16:3000/packages/htmljs.js?567eb96d5d22631c03d6aca6afa4c42f0d1295f2:116:1
.visitAttribute@http://192.168.1.16:3000/packages/htmljs.js?567eb96d5d22631c03d6aca6afa4c42f0d1295f2:245:12
.visitAttribute@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2127:1
.visitAttributes@http://192.168.1.16:3000/packages/htmljs.js?567eb96d5d22631c03d6aca6afa4c42f0d1295f2:228:24
.visitAttributes@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2119:12
Blaze._expandAttributes@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2147:1
materializeTag/updateAttributes@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1520:27
viewAutorun/</<@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1865:16
Template._withTemplateInstanceFunc@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3476:12
viewAutorun/<@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1864:1
Blaze._withCurrentView@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2197:12
viewAutorun@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1863:1
Tracker.Computation.prototype._compute@http://192.168.1.16:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:327:5
Tracker.Computation@http://192.168.1.16:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:243:5
Tracker.autorun@http://192.168.1.16:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:566:11
Blaze.View.prototype.autorun@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1875:14
materializeTag@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1533:9
materializeDOMInner@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1449:24
Blaze._materializeDOM@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1428:7
doMaterialize@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2017:32
Tracker.nonreactive@http://192.168.1.16:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:593:12
doRender@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2015:9
viewAutorun/</<@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1865:16
Template._withTemplateInstanceFunc@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3476:12
viewAutorun/<@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1864:1
Blaze._withCurrentView@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2197:12
viewAutorun@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1863:1
Tracker.Computation.prototype._compute@http://192.168.1.16:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:327:5
Tracker.Computation.prototype._recompute@http://192.168.1.16:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:346:9
Tracker._runFlush@http://192.168.1.16:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:485:9
onGlobalMessage@http://192.168.1.16:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:372:11
" meteor.js:888:10
"Exception from Tracker recompute function:" meteor.js:888:10
"Error: No such function: isActiveRoute" meteor.js:888:10
"Blaze.View.prototype.lookup/<@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2982:1
Spacebars.call@http://192.168.1.16:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:172:12
Spacebars.mustacheImpl@http://192.168.1.16:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:109:10
Spacebars.mustache@http://192.168.1.16:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:113:16
Template.adminSidebar</</<.class@http://192.168.1.16:3000/packages/orionjs_bootstrap.js?3d2e27ea4f17b6d627eebb8dcfc3852fa8e3a4d2:727:1
Blaze._withCurrentView@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2197:12
.visitAttribute@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2125:1
.visitAttributes@http://192.168.1.16:3000/packages/htmljs.js?567eb96d5d22631c03d6aca6afa4c42f0d1295f2:228:24
.visitAttributes@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2119:12
Blaze._expandAttributes@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2147:1
materializeTag/updateAttributes@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1520:27
viewAutorun/</<@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1865:16
Template._withTemplateInstanceFunc@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3476:12
viewAutorun/<@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1864:1
Blaze._withCurrentView@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2197:12
viewAutorun@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1863:1
Tracker.Computation.prototype._compute@http://192.168.1.16:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:327:5
Tracker.Computation@http://192.168.1.16:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:243:5
Tracker.autorun@http://192.168.1.16:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:566:11
Blaze.View.prototype.autorun@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1875:14
materializeTag@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1533:9
materializeDOMInner@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1449:24
Blaze._materializeDOM@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1428:7
doMaterialize@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2017:32
Tracker.nonreactive@http://192.168.1.16:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:593:12
doRender@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2015:9
viewAutorun/</<@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1865:16
Template._withTemplateInstanceFunc@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3476:12
viewAutorun/<@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1864:1
Blaze._withCurrentView@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2197:12
viewAutorun@http://192.168.1.16:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1863:1
Tracker.Computation.prototype._compute@http://192.168.1.16:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:327:5
Tracker.Computation.prototype._recompute@http://192.168.1.16:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:346:9
Tracker._runFlush@http://192.168.1.16:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:485:9
onGlobalMessage@http://192.168.1.16:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:372:11
" meteor.js:888:10

**Comment by kevohagan** [comment]
@nicolaslopezj you need to update the dependency of zimme:iron-router-active from 1.0.0  to 1.0.4
in core

**Comment by nicolaslopezj** [comment]
Thanks @kevohagan

**Comment by SICCVI** [comment]
merci! Je comprends que vous avez trouvé la solution; mais comment puis je l'appliquer de mon côté ? Je débute avec l'ecosysteme node.js.

**Comment by nicolaslopezj** [comment]
run ```meteor update```

**Comment by SICCVI** [comment]
Thank you, it's simple .... but it still does not work. Same errors reported in the console.
Always blank page after creating the admin account. By testing in a private session (chrome, firefox) I am routed to http://192.168.1.16:3000/admin/dictionary that displays the login page. When I click on sign in, nothing happens.

Uncaught ReferenceError: s is not defined
debug.js:41 
Exception from Tracker recompute function:
debug.js:41 Error: No such function: isActiveRoute
    
at lookup.js:125
    
at Spacebars.call (spacebars-runtime.js:130)
    
at Spacebars.mustacheImpl (spacebars-runtime.js:67)
    
at Object.Spacebars.mustache (spacebars-runtime.js:71)
    
at HTML.LI.class (base.html:157)
    
at Object.Blaze._withCurrentView (view.js:523)
    
at Blaze._HTMLJSExpander.def.visitAttribute (view.js:451)
    
at HTML.TransformingVisitor.def.visitAttributes (visitors.js:171)
    
at Blaze._HTMLJSExpander.def.visitAttributes (view.js:445)
    
at Object.Blaze._expandAttributes (view.js:474)

For information :
---------------------------------------

Ubuntu server 14.04
MongoDB shell version: 2.4.9
node v0.10.37

After meteor add orionjs:bootstrap

accounts-base                       added, version 1.2.0
accounts-password                   added, version 1.1.1
aldeed:autoform                     added, version 5.1.2
aldeed:collection2                  added, version 2.0.1
aldeed:delete-button                added, version 1.0.0
aldeed:simple-schema                added, version 1.1.0
aldeed:tabular                      added, version 1.1.0
coffeescript                        added, version 1.0.6
dburles:collection-helpers          added, version 1.0.3
email                               added, version 1.0.6
iron:controller                     added, version 1.0.7
iron:core                           added, version 1.0.7
iron:dynamic-template               added, version 1.0.7
iron:layout                         added, version 1.0.7
iron:location                       added, version 1.0.7
iron:middleware-stack               added, version 1.0.7
iron:router                         added, version 1.0.7
iron:url                            added, version 1.0.7
less                                added, version 1.0.14
localstorage                        added, version 1.0.3
manuelschoebel:ms-seo               added, version 0.4.1
matb33:collection-hooks             added, version 0.7.11
meteorhacks:inject-initial          added, version 1.0.2
meteorhacks:subs-manager            added, version 1.2.4
momentjs:moment                     added, version 2.8.4
mongo-livedata                      added, version 1.0.8
npm-bcrypt                          added, version 0.7.8_2
orionjs:bootstrap                   added, version 0.1.4
orionjs:core                        added, version 0.7.6
service-configuration               added, version 1.0.4
sha                                 added, version 1.0.3
softwarerero:accounts-t9n           added, version 1.0.9
srp                                 added, version 1.0.3
underscorestring:underscore.string  added, version 2.4.0
useraccounts:bootstrap              added, version 1.2.3
useraccounts:core                   added, version 1.8.1
zimme:iron-router-active            added, version 1.0.3 <---- you write 1.04


si@dev-meteor:~/test-orion$ meteor update
This project is already at Meteor 1.1.0.2, the latest release.
Your packages are at their latest compatible versions.


I hope that could help you

**Comment by rwatts3** [comment]
Hello @SICCVI I'm sorry you are still having this issue. If you could give me about 15 minutes I will upload a full working copy for you to clone and start hacking away.

**Comment by rwatts3** [comment]
Please note that `v1.0` is still in beta, and the full functionality has not been completed, but @nicolaslopezj is working on the release and the full release will be available soon, but for the time being i'll upload the beta for you to work with for now.

**Comment by SICCVI** [comment]
You are hyperactive, thank you. No problem, take the necessary time. I stay listening. I would like to help but I feel completely dumped by Node.js

**Comment by rwatts3** [comment]
Alright @SICCVI take a look at this issue. 
For anyone else having issues getting the example blog v1.0 beta working simply clone this repository and fire away. 

#108 

https://github.com/rwatts3/example-blog-v1.0-beta

**Comment by SICCVI** [comment]
Thanks very much!!

**Comment by rwatts3** [comment]
No problem. Let me know if you need any help.  In the meantime I'm going to get some shut eye it's 3 AM here :)

**Comment by SICCVI** [comment]
Ok thanks, Fais un gros dodo ...
