### ISSUE TITLE
Example Blog | Orion v1.0 Beta Working Example

### ISSUE THREAD

**Issue by rwatts3** [orionjs/orion#108]
Here is a link to a repository with a fully working example for Orion v1.0 beta testers. 
I have already taken care of pulling in the v1.0 packages , and updating the example to work with the new package examples. 

For anyone wanting to do beta testing . simply clone this repo , and fire up meteor. 
https://github.com/rwatts3/example-blog-v1.0-beta

**Comment by timfam** [comment]
Thanks buddy

**Comment by maxfinnsjo** [comment]
Im am using to much joy, but I cant seem to upload images!

**Comment by timfam** [comment]
@maxfinnsjo  what package are using s3 or local packages?

**Comment by nicolaslopezj** [comment]
If you use s3 there is a new configuration

**Comment by maxfinnsjo** [comment]
i use s3 have put in api key, secret and bucket name, from user ami of aws account in admin..  but gives "Error": in console when trying to upload selected image file

**Comment by rwatts3** [comment]
@maxfinnsjo 

Would you submit a new issue.  Add the error code , and mention me in the issue.  This initial issue is seperate from the issue you're having.
