### ISSUE TITLE
Gitter.im for open discussion for Orion

### ISSUE THREAD

**Issue by rwatts3** [orionjs/orion#109]
I just came across <http://gitter.im> in a repository I was researching on atmospherejs.com . I believe this would be a cool place, to have open discussions, about the project without cluttering the issues. Then if a discussion comes up that should be mentioned in the actual repo, we could refer the person to the repository to create an issue. I believe gitter.im also allows you to go directly to the repo to create an issue. 

Let me know your thoughts.

**Comment by timfam** [comment]
I discussed chat with Nick a while back and we are thinking of either irc
plus etherpad. Meteor has an irc channel maybe we should piggyback on that.

**Comment by rwatts3** [comment]
Yeah I remember the discussion on about etherpad. Mind if I ask the why not gitter.im , trying to see if there is any underlying issues or dislikes before I start using it on other repos.

**Comment by timfam** [comment]
Never tried it maybe more modern than freenode  irc. The thing to note
though is majority of opensource projects use irc and meteor does too.
Again gitter is paid right?

**Comment by rwatts3** [comment]
No gitter is free for public chats and 25 members for private discussions . So only 25 in a private discussion which I never see if hitting that limit for s private discussion.  Most of the discussions are on the issue system here and they're all public .

The pro version has the exact same settings except you get unlimited private users in a discussion.  And it's $5

**Comment by timfam** [comment]
Okay then setup a room and let's start collabNation :)
