### ISSUE TITLE
Error in the first setup

### ISSUE THREAD

**Issue by ahmetcetin** [orionjs/orion#112]
I'm using Meteor 1.2.2. I tried to install orion bootstrap as described locally on my mac. After creating a new meteor app, and cleaning the sample files of meteor, here what I've done:

1. meteor add orionjs:bootstrap
2. meteor add twbs:bootstrap
3. meteor add fort awesome:fontawesome

After running meteor, and navigating to /admin, it redirects to /admin/setup, and it shows the following error in console:
![developer_tools_-_http___localhost_9000_admin](https://cloud.githubusercontent.com/assets/5046786/7229232/9cc35f0c-e761-11e4-9da8-97eacb350420.png)

Anyway, I've tried to create the first user, it looks like nothing happened, it shows the same new user form but the address changes to /admin/change-password and it gives the following error in console:

![developer_tools_-_http___localhost_9000_admin](https://cloud.githubusercontent.com/assets/5046786/7229263/17234802-e762-11e4-8eb1-60bbc3982f2f.png)

So, I thought, somehow maybe I should enter different password, and I entered a password includes mixed case letters, numbers and exclamation mark, now it shows totally blank page, and the address bar changes to:

http://localhost:9000/admin/change-password?email=admin%40mydomain.com&name=admin&password=mixED112233%21&password-confirm=mixED112233%21

And it gives the following error in the console:

![developer_tools_-_http___localhost_9000_admin_change-password_email_admin_40cetin_info_name_admin_password_ac1271ap_21_password-confirm_ac1271ap_21](https://cloud.githubusercontent.com/assets/5046786/7229348/f06184b2-e762-11e4-9fec-eb42b6df5dff.png)

Then, when I try to open /admin, it reroutes to /admin/change-password, but nothing shows on the page. And in the console, it gives the following error:

![developer_tools_-_http___localhost_9000_admin](https://cloud.githubusercontent.com/assets/5046786/7229400/83dc012c-e763-11e4-885a-ab7bf3266fa7.png)

And I have tried it in several times, with meteor reset or in another folder, but the result is the same.

So, am I missing anything or is there a known bug? If so, how can I install and test orion properly?
Cheers,
Ahmet Cetin

**Comment by ahmetcetin** [comment]
btw, if it helps, when I run meteor first time after installing orion, it shows these lines after App running message in the command prompt:

I20150420-13:26:24.537(2)? Orion config initialized.
I20150420-13:26:24.539(2)? Dictionary initialized.

**Comment by nicolaslopezj** [comment]
This seems to be an error with ```zimme:iron-router-active```. 
Try doing ```meteor add zimme:iron-router-active``` and meteor update.

**Comment by ahmetcetin** [comment]
Thanks, I've done and now it shows change password screen, but I cannot see other parts of the admin screen, like dictionary, entity, etc. 
![screenshot_21_04_15_12_09](https://cloud.githubusercontent.com/assets/5046786/7250070/61eb711c-e81f-11e4-96ef-e9ea0dd3dba4.png)
I already added all packages installed by orion one by one and run meteor update, but didn't help. In the console I see this:
![developer_tools_-_http___localhost_9000_admin](https://cloud.githubusercontent.com/assets/5046786/7250085/8cc3b99e-e81f-11e4-8298-d986cc7c8e5e.png)
Any idea?

**Comment by nicolaslopezj** [comment]
You must declare the entities and the dictionary first

**Comment by timfam** [comment]
Take a look at the posts entity in the example blog

**Comment by ahmetcetin** [comment]
Thank you guys! The example blog project helped me a lot for kick-off.
