### ISSUE TITLE
example blog:  error: unknown package in top-level dependencies: orionjs:froala

### ISSUE THREAD

**Issue by mraak** [orionjs/orion#118]
Trying to run v1.0, any idea why I'm getting this?

**Comment by mraak** [comment]
Is there at least a workaround?

**Comment by timfam** [comment]
simply remove that package from the .meteor/packages file

**Comment by timfam** [comment]
That error should not exist if you downloaded and added v1.0 of orion all the packages are there. @mraak did you do this?

**Comment by mraak** [comment]
I followed the instructions given by you in this thread: https://github.com/orionjs/orion/pull/81. 

"everything is in there just download and run"

So this is what I did:

~/Projects/Code/orionjs → git clone https://github.com/orionjs/example-blog.git
Cloning into 'example-blog'...
remote: Counting objects: 395, done.
remote: Total 395 (delta 0), reused 0 (delta 0), pack-reused 395
Receiving objects: 100% (395/395), 50.52 KiB | 0 bytes/s, done.
Resolving deltas: 100% (177/177), done.
Checking connectivity... done.
~/Projects/Code/orionjs → cd example-blog/
~/Projects/Code/orionjs/example-blog(master) → git checkout v1.0
Branch v1.0 set up to track remote branch v1.0 from origin.
Switched to a new branch 'v1.0'
~/Projects/Code/orionjs/example-blog(v1.0) → meteor
[[[[[ ~/Projects/Code/orionjs/example-blog ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: unknown package in top-level dependencies: orionjs:froala
   
=> Your application has errors. Waiting for file change.

**Comment by nicolaslopezj** [comment]
@mraak You must put the packages in the packages folder because orion 1.0 is not on atmosphere.
You must download the #81 branch and put all the packages in the packages folder of your app.

Look how @rwatts3 did it here https://github.com/rwatts3/example-blog-v1.0-beta

**Comment by rwatts3** [comment]
I will update the beta repo tonight with the latest updates from the 1.0 branch.  Keep in mind 1.0 is in final testing and will launch soon.

**Comment by mraak** [comment]
@rwatts3 So in your example-blog-beta, there's no need to manually copy packages?

**Comment by rwatts3** [comment]
Correct.  If you look at the repo you will see the packages are already there.

**Comment by mraak** [comment]
Ok, also great to hear 1.0 is nearly ready, any ETA?

**Comment by rwatts3** [comment]
Orion v1.0 is now released. follow the documentation at [orionjs.org](http://orionjs.org/docs)
