### ISSUE TITLE
Telescope and Orion

### ISSUE THREAD

**Issue by vonwao** [orionjs/orion#119]
Has anyone looked at how to possibly integrate Orion with Telescope? (point the telescope towards Orion, lol). 

You may ask "why", I'm building a community-based platform and instead of reinventing the wheel I would rather just reuse some of that Telescope code.  What I imagine is replace the security, user, permission system of telescope with Orion's, because I want the nice configurable admin panel that Orion offers.

**Comment by timfam** [comment]
@vonwao point the telescope team to Orion and sell  them on the benefit, be an Orion evangelist :)

**Comment by vonwao** [comment]
Yes, good idea :)  I decided to delete/close this issue for now because I thought I should do some more research on this for now and not introduce too much noise into the issues with new ideas.
