### ISSUE TITLE
Migrating collections?

### ISSUE THREAD

**Issue by mraak** [orionjs/orion#122]
Say I want to rename my Companies into Organizations and add / remove some fields.

**Comment by timfam** [comment]
Create a new company collection then insert only the new fields

**Comment by nicolaslopezj** [comment]
Please provide more details @mraak

**Comment by mraak** [comment]
There's an organized way of doing migrations and storing them for later reversal in, say, Django framework there are both inbuild tools, and 3rd party tools such as South.

https://docs.djangoproject.com/en/1.8/topics/migrations/

http://south.readthedocs.org/en/latest/commands.html


I was wondering if there's anything similar for Meteor or Orion.
