### ISSUE TITLE
 there's no route on the client or the server for url

### ISSUE THREAD

**Issue by SICCVI** [orionjs/orion#124]
Hi,

First of all thank you for all your work and Orion in version 1.0. So I just installed it and I have this message: 

> Oops, looks like there's no route on the client or the server for url: "http://192.168.1.16:3000/."

Orion is installed on a vm ubuntu server.

Thanks

**Comment by timfam** [comment]
You have to use the example-blog to get a working front end or implement yours orionjs server packages only add admin/backend for you

**Comment by SICCVI** [comment]
Ok ok Thanks
