### ISSUE TITLE
Materialize date input broken

### ISSUE THREAD

**Issue by jdivy** [orionjs/orion#127]
I cranked up a demo project and used a date field when defining my schema like so:

```javascript
Services = new orion.collection('services', {
    singularName: 'service',
    pluralName: 'services',
    link: {
        title: 'Services'
    },
    tabular: {
        columns: [
            {data: 'serviceDate', title: 'Service Date'}
        ]
    }
});

Services.attachSchema(new SimpleSchema({
    serviceDate: {
        label: 'Date',
        type: Date
    }
}));
```

The result is an unresponsive date input on the create form.  I'm not entirely sure whether this is an issue to be solved inside `orion` or `AutoForm`, and I didn't have too much time to dig deeper, but I did find a round-about way of fixing the issue by adding the following code to the client side:

```javascript
AutoForm.addHooks('orionMaterializeCollectionsCreateForm', {
    formToDoc: function(doc){
        var datefields = $('input[type="date"]');
        datefields.on('click', function (e) {
            // according to materializecss docs, this is how we 'pick a date'
            $(e.target).pickadate({
                format: 'yyyy-mm-dd' // format necessary for autoform to take it...
            });
        });
        return doc;
    }
});
```
Maybe you can shed some light on where this could (or should) be fixed?

**Comment by timfam** [comment]
I will start with autoform issue queue first, Autoform and SimpleSchema are used wholesale here and you   should not need client hacks to make it work

**Comment by nicolaslopezj** [comment]
@jdivy you should submit a issue on this package https://github.com/djhi/meteor-autoform-materialize/

**Comment by jdivy** [comment]
Turns out it was my problem (and partly lack of documentation perhaps).  Found my answer here https://github.com/djhi/meteor-autoform-materialize#pickadate

My hack is completely unnecessary - by configuring `autoform` with `type: "pickadate"` (which is provided by the package @nicolaslopezj pointed me to) all works as expected:

```javascript
Services.attachSchema(new SimpleSchema({
    serviceDate: {
        type: Date,
        autoform: {
            type: 'pickadate'
        }
    }
}));
```
