### ISSUE TITLE
Collection attribute button in index view

### ISSUE THREAD

**Issue by ryanbuiltthat** [orionjs/orion#128]
I may be just hallucinating but I thought I saw somewhere in the previous docs where we could add a custom action button in the ~~entity~~ collection index view? I need a quick way to remove ~~entities~~ collections from the index table. That way I don't have to open each one, hit delete, confirm, etc.  The ideal solution is a check box so I can do bulk actions but at this point, an action button is the quick fix I need.

**Comment by ryanbuiltthat** [comment]
Actually this was way easier than I thought thanks to Tabular. Within the collection definition I added this to the Tabular object setup:

    tableColumns: [
		{
		  tmpl: Meteor.isClient && Template.receiptactionbtn,
		  title: 'Action'
		},

Then I just have a series of buttons in my `receiptactionbtn` template with the right helpers. If I can get my template overrides to work I'll work to get my checkbox selection working for bulk actions. Baby steps.... :)

**Comment by timfam** [comment]
I agree checkboxes are the way to go, but this should be a package. I will discuss with the others about this
