### ISSUE TITLE
How do I add a license for Frola?

### ISSUE THREAD

**Issue by ryanbuiltthat** [orionjs/orion#129]
Where would I add the license for frola? They have two methods, both seem to need DOM access. Is it just a matter of writing another helper for admin pages and use the `Template.onRendered` hook?

From the docs:

> In order to active the license you have purchased generate a key below and then add the following code after you include the editor JS files.
 ```javascript
 <script>
      $.Editable.DEFAULTS.key = 'ACTIVATION_KEY';
  </script>
```
> **OR**, pass the key as an option when you initialize the editor.
```javascript   
 <script>
      $(your_selector).editable({key: 'ACTIVATION_KEY'});
 </script>
```

I'm not sure how I'd go about the first method given how meteor loads javascript and the second would need to be template specific it seems.

**Comment by ryanbuiltthat** [comment]
Seems like in the frola subpackage in `frola.ja` couldn't we add a config variable after line 14:

```javascript
  // set the current value of the attribute
  element.editable("setHTML", this.data.value, true);

  // set key if exists
  element.editable({key: orion.config.get('FROLA_ACTIVATION_KEY')});
```
Add app config variable:
```javascript
   orion.config.add('FROLA_ACTIVATION_KEY', 'System', {secret: true})
```

I'm not at my dev machine to test this but that seems like that should work no? Put the inputs in for any keys needed automatically...if a user really wants you can always set a boolean var to hid un-needed config variables.

**Comment by ryanbuiltthat** [comment]
To further detail this idea, I think any attributes for the system that are native should be prepackaged under a System category or whatever. Subpackages are great and allow some awesome flexibility but for the ones that require some configuration, adding them to a general config category would help group required system configuration variables and provide a more consistent UX for admins....IMHO that is. 

For packages like the S3 that's easy to do, but something like Frola where the activation key seems to need some specific placement, it'd be nice to be able to have those variables loaded up and ready for values upon installing the package.

**Comment by timfam** [comment]
You have a good point here. We will try to make it so

**Comment by timfam** [comment]
for now I think onRendered should solve your problem

**Comment by ryanbuiltthat** [comment]
@timfam  the way meteor handles the onRendered event and the way it scopes variables wouldn't I need to put that activation in every template that could or does display the Frola editor?

**Comment by timfam** [comment]
yes but you can make a global var in /lib/options.js and call in every template instance. Also might be possible to pass it through the schema as a default value or something of that nature and you won't have to bother with onRendered @nicolaslopezj  this should be possible?

**Comment by nicolaslopezj** [comment]
@ryanbuiltthat The solution you pointed up is perfect. Would you like to make a pull request?

**Comment by ryanbuiltthat** [comment]
Hey guys, apologies I've been playing catch up and haven't had time to get to this. Do you still need a PR for this? I also have a small enhancement that adds a third field to config vars. A label. Sometimes you may need a multi-word label and I was hitting issues with the current state. (Then again I haven't updated in 15 days).
