### ISSUE TITLE
Languages in v1.0 

### ISSUE THREAD

**Issue by jorisroling** [orionjs/orion#132]
In v1.0 I dearly miss the language option of the dictionary. Any chance that will return?

**Comment by timfam** [comment]
Internationalization will return, we're figuring out the best way to use an exiting package to achieve that

**Comment by jorisroling** [comment]
Great! Any clue about a timeframe? (don't want to be pushy, but I was about to release an app...)

**Comment by timfam** [comment]
It's a matter of testing out different packages out there, could you join in the hunt for the right package to use?

**Comment by timfam** [comment]
Messageformat is a possible https://atmospherejs.com/gadicohen/messageformat option http://messageformat.meteor.com/

**Comment by jorisroling** [comment]
In my view, there are so many aspects to true localisation and internationalisation, Orion will never solve them all adequately, for everyone. Think dates, numbers, text etc. The simple solution Orion provided in it's former life was a good start, and should even be used, in my view, for collections (previously entities). Maybe an extra option to it could be to allow only certain (text) fields to be 'translatable', and so prevent doubling everything. 




My 2 cents... 😊



—

**Comment by jorisroling** [comment]
Hi Nicolas,

Any chance you could get your old **Language** features (in _Dictionaries_ and possibly _Collections_ & _Pages_) back in? So that a **english** and (in my case) **dutch** buttons appears above the AutoForms?

Would be grand! 

Regards,
J*

**Comment by nicolaslopezj** [comment]
Doing this is in the roadmap, but it has to be done the right way. 
This features changes a lot of things from the inside, so we need to do it perfectly.

**Comment by nicolaslopezj** [comment]
We will keep just #6
