### ISSUE TITLE
Example Blog (https://github.com/orionjs/examples)

### ISSUE THREAD

**Issue by maxfinnsjo** [orionjs/orion#134]
I Clone this gitbub repo in to a directory, and cd in to the Blog folder, I run "meteor" the example blog opens in my browser on localhost:3000, I can create a user and log in to admin view. I add post and try to add image, I can click on add image and save upload. But no image shows up in the post, either in the edit when actually selecting image to upload nor when it has been saved.. Upon saving my console in chrome gives me "Error:" simply that. 

Same problem goes for trying to change the logo, adding any images via the upload image functionality.  

I am happy to try and go through the above process again or try another way of getting this to work! Thanks for all the hard work you guys are doing! Shoutout to @rwatts3 for schooling me on how to use the ticket system correct ;-) big up guys!!

**Comment by nicolaslopezj** [comment]
Did you setup the s3 config?

**Comment by maxfinnsjo** [comment]
i redid all as in the updated readme url regarding s3 config. Now it works!! Great work guys, thanks!!
