### ISSUE TITLE
S3 address

### ISSUE THREAD

**Issue by smogg** [orionjs/orion#135]
When trying to upload a file I get a cross-origin request blocked response, even tho my CORS on aws are set. According to [this StackOverflow questions](http://stackoverflow.com/a/15052967/704247) the endpoint address should be http://bucket.s3.amazonaws.com/ and not http://s3.amazonaws.com/bucket/ in order for CORS to be respected. The error I get back says otherwise, where can I change that?

**Comment by nicolaslopezj** [comment]
Orion uses https://github.com/Lepozepo/S3. That package returns the url in the way you are seeing it, if you want to change you can remove the s3 package and put the modified contents of the package in you code. https://github.com/orionjs/orion/blob/master/packages/s3/s3.js

**Comment by sokki** [comment]
@nicolaslopezj The package allow the parameter "region" and switch to the subdomain urls, if it's not "us-standard" https://github.com/Lepozepo/S3/blob/345971c472fef17cbd40cf278c6d476df1763116/server/sign_request.coffee#L43
You should implement the region Setting in orion-s3. 

@smogg Use a bucket in region "us-standard" until it's fixed

**Comment by smogg** [comment]
Thanks for the clarification, everything works as expected now.
