### ISSUE TITLE
Ability to sort createdAt attribute in collections index table

### ISSUE THREAD

**Issue by frabrunelle** [orionjs/orion#136]
I'd like to be able to sort the createdAt attribute in the index table of a collection. For example, I have a transactions collection and I would like the index table to display the transactions in order of most recent date.

When I put `orion.attributeColumn('createdAt', 'createdAt', 'Date')` in the columns array, I am not able to sort the Date column (`sorting_disabled`).

![screen shot 2015-05-05 at 6 30 24 am](https://cloud.githubusercontent.com/assets/1114844/7471038/448c47dc-f2f0-11e4-8b5a-14b022f8b1f7.png)

When I put `{ data: 'createdAt', title: 'Date' }` in the columns array, I am able to sort the Date column, but the format of the date is not very pretty and takes too much space. It could be more concise. Also, the order is ascending but I want it to be descending so as to show the most recent transactions first.

![screen shot 2015-05-05 at 6 35 11 am](https://cloud.githubusercontent.com/assets/1114844/7471136/5c25b936-f2f1-11e4-9110-79e112e3d658.png)

Would it be possible to display the createdAt via `orion.attributeColumn('createdAt', 'createdAt', 'Date')` in such a way that the sorting gets enabled?

Thanks for making Orion :heart: , it's truly amazing  :smile: .

**Comment by frabrunelle** [comment]
It seems like the [datetime-moment](https://datatables.net/plug-ins/sorting/datetime-moment) plugin for DataTables would enable such a functionality.

See this blog post for more info: https://datatables.net/blog/2014-12-18

Since Orion already uses [moment.js](http://momentjs.com), which is a dependancy of the `datetime-moment` plugin, I think it would make sense to include that plugin in Orion. That way we could enable sorting for `orion.attributeColumn('createdAt', 'createdAt', 'Date')`.

**Comment by timfam** [comment]
@frabrunelle you can do a PR for this. I am also thinking of doing accounting formating package when I have the time. So PR is your best friend

**Comment by frabrunelle** [comment]
@timfam alright, I'll try to do a PR :smile:

for an accounting formatting package, have you looked at http://openexchangerates.github.io/accounting.js/ (available via https://atmospherejs.com/risul/accounting for example)?

**Comment by timfam** [comment]
Yes that is what I have in mind

**Comment by frabrunelle** [comment]
I actually found a way to achieve what I wanted by looking at the [example](https://github.com/aldeed/meteor-tabular#example) in the README of meteor-tabular.

```
{
  data: "lastCheckedOut",
  title: "Last Checkout",
  render: function (val, type, doc) {
    if (val instanceof Date) {
      return moment(val).calendar();
    } else {
      return "Never";
    }
  }
}
```

So I'll close this issue for now.

**Comment by anthonylebrun** [comment]
Nice solution! Only it seems moment isn't defined at the time of calling.
