### ISSUE TITLE
Error installing orionjs:core@1.0.0

### ISSUE THREAD

**Issue by RubenB** [orionjs/orion#138]
I get this contraint error when i try to install orionjs:core@1.0.0. If i try 'meteor add orionjs:core', meteor adds the previous version of orionjs:core. Am I missing something or is this a bug?

I tried this on a fresh project and I also use windows 8.1.

error: Conflict: Constraint matb33:collection-hooks@0.7.13 is not
satisfied by matb33:collection-hooks 0.7.11.
Constraints on package "matb33:collection-hooks":
* matb33:collection-hooks@0.7.11 <- orionjs:accounts 1.0.3 <- orionjs:core
1.0.0
* matb33:collection-hooks@0.7.13 <- orionjs:config 1.0.1 <- orionjs:core
1.0.0

**Comment by rwatts3** [comment]
I would run meteor reset, or I would delete the versions, and uninstall all variants of Orion, if you have a previous version of config or account it will force you to use the compatible version of Orion.

**Comment by RubenB** [comment]
My problem is solved! It probably had something to do with meteor 1.2.2 rc.
I started a new project on my mac with meteor version 1.2.2 instead of 1.2.2 rc. 
I added orionjs:core and it was version 1.0.0. 

Thanks for the help @rwatts3 !
