### ISSUE TITLE
Separating admin and frontend

### ISSUE THREAD

**Issue by delgermurun** [orionjs/orion#141]
[Incremental loading](https://trello.com/c/24s6vyxo/55-incremental-loading) is not top priority for `MDG`, so it'll take a while to implemented.

I don't want to load whole admin related things (dashboard etc...) for readers. They absolutely doesn't need it.

Can I separate it?

**Comment by nicolaslopezj** [comment]
In a simple solution, no, you can't.

But I can think that you could make 2 different apps, and here two different solutions:

- Make the both apps connect to the same mongo database, then only put orion in one.
- Make the second app connect to the orion app via ddp http://docs.meteor.com/#/full/ddp_connect.

**Comment by timfam** [comment]
I read through that incremental loading topic and I think there might be an easier way to solve this problem for Orion starting with the themes, what if we place theme files in public dir
```
onStartup
mv /theme-folder/subfolders to /public/theme-folder/subfolders
```
in packages.js for theme we add a connect file
```
if route.path === admin/*
uncomment links to /public/theme
```
this way Meteor never loads admin themes until when needed
thoughts?

**Comment by delgermurun** [comment]
Thank you guys for the ideas. I'll do some workaround and let you know the result.

@timfam Sorry, I can't fully understand your idea. If possible, little demo would be great :). Thanks.

**Comment by delgermurun** [comment]
Looks like `DDP.connect` is way to go.

**Comment by timfam** [comment]
So you got that working great! Can you do a tutorial or share something about the challenges you faced doing this with Orion?

**Comment by delgermurun** [comment]
I did little demo that connects to http://orion-example.meteor.com/. It works great.

I wish I could write articles on English. My English isn't good enough, especially writing/speaking skills. So I can't do it now, sorry.

**Comment by timfam** [comment]
Then write what you can and I can fix the typos.  Good practice too :)

**Comment by delgermurun** [comment]
@timfam I'll think about it :)
