### ISSUE TITLE
Added support for gridFS for Orion

### ISSUE THREAD

**Issue by Weijtmans** [orionjs/orion#144]
Hi,

I've created a package to add support for gridFS. Feel free to incorporate it in Orion.
It's available at: https://github.com/brightbind/orion-gridFS/

Best,

Elgar

**Comment by timfam** [comment]
Thanks @Weijtmans for the package very useful

**Comment by nicolaslopezj** [comment]
Thats great! I will add it to the list of Community Add-On Packages

**Comment by PEM--** [comment]
Yummy :+1:
