### ISSUE TITLE
Add a class to an attribute..

### ISSUE THREAD

**Issue by payner35** [orionjs/orion#146]
```
	companyId: orion.attribute('hasOne',
		label: 'Company'
	,
		collection: Company
		titleField: 'title'
		publicationName: 'hasOneCompany'
	)
```
I have a HasOne relationship linking to a Company.  This results in a dropdown like so

![image](https://cloud.githubusercontent.com/assets/939749/7631736/166403a4-fa57-11e4-9b12-543cf02c5990.png)

The company here is called "oneLife"...  i want to add a class "active" to  the input field..  Can i add a class to the schema?

**Comment by nicolaslopezj** [comment]
We are waiting here
https://github.com/djhi/meteor-autoform-materialize/issues/18

**Comment by payner35** [comment]
This is fixed now at source?
