### ISSUE TITLE
How To: Make changes in orion package and use it in your project?

### ISSUE THREAD

**Issue by mraak** [orionjs/orion#148]
I'd like to make amendments in orion/packages/accounts, and orion/packages/bootstrap, and then use it in my own version of examples/blog. Do I have to compile it somehow, just copy these packages somewhere (where)?

Furthermore, in the list of packages for blog example doesn't include accounts, how is this handled?

**Comment by timfam** [comment]
Accounts is a dependent of core. you can download core and user it locally

**Comment by mraak** [comment]
@timfam And the first question? How do I use orionjs/accounts after making some changes to it? Copy it into my project manually (where), or?

**Comment by nicolaslopezj** [comment]
If you put it in the packages folder of your project, meteor will take that one instead of the original.

```
myApp/packages/accounts/package.js
```

If you wan't to change bootstrap, you can override the templates in a easy way.

**Comment by rwatts3** [comment]
Also you can dork the package.  And add Orion repo as an upstream.  As you develop and as the package is updated you can pull and merge the latest update from the upstream and continue your development.

**Comment by mraak** [comment]
Say I wanted to make a change worthy of a pull request, what branch should I be using? I see both master and 1.1 have active commits happening.

**Comment by rwatts3** [comment]
I'd say Master.  1.1 is for new functionality or minor improvements coming
to Orion.  Nick correct me if I'm wrong here.

On Wednesday, May 20, 2015, mraak <notifications@github.com> wrote:

> Say I wanted to make a change worthy of a pull request, what branch should
> I be using? I see both master and 1.1 have active commits happening.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orionjs/orion/issues/148#issuecomment-103830493>.
>


-- 
Ryan Watts
E.ryandwatts@gmail.com
C.520-442-8962
F.520-437-0914
IN. https://www.linkedin.com/in/ryandwatts

**Comment by mraak** [comment]
The one I'm doing is pretty huge, better admin for users / accounts. So it might need more reviewing and possibly redesigning something.

**Comment by rwatts3** [comment]
Oh I see.  Did you consider making a separate package instead of PR ? If
it's that huge ?

On Wednesday, May 20, 2015, mraak <notifications@github.com> wrote:

> The one I'm doing is pretty huge, better admin for users / accounts. So it
> might need more reviewing and possibly redesigning something.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orionjs/orion/issues/148#issuecomment-103919255>.
>


-- 
Ryan Watts
E.ryandwatts@gmail.com
C.520-442-8962
F.520-437-0914
IN. https://www.linkedin.com/in/ryandwatts

**Comment by rwatts3** [comment]
As a rule of thumb unless you have ore approval from Nick about submitting
PR to Core , we try to keep things in packages.

On Wednesday, May 20, 2015, Ryan Watts <ryandwatts@gmail.com> wrote:

> Oh I see.  Did you consider making a separate package instead of PR ? If
> it's that huge ?
>
> On Wednesday, May 20, 2015, mraak <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> The one I'm doing is pretty huge, better admin for users / accounts. So
>> it might need more reviewing and possibly redesigning something.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/orionjs/orion/issues/148#issuecomment-103919255>.
>>
>
>
> --
> Ryan Watts
> E.ryandwatts@gmail.com
> <javascript:_e(%7B%7D,'cvml','E.ryandwatts@gmail.com');>
> C.520-442-8962
> F.520-437-0914
> IN. https://www.linkedin.com/in/ryandwatts
>
>
>

-- 
Ryan Watts
E.ryandwatts@gmail.com
C.520-442-8962
F.520-437-0914
IN. https://www.linkedin.com/in/ryandwatts

**Comment by mraak** [comment]
It's not that "huge", but it touches many other parts of accounts package as well as bootstrap package (would also need to do the same in materialize).

Basically, instead of only sending invites, admin can also create the user, and later delete or edit it, change password, etc... The user gets an activation email to select a password, but he is already created and editable in the system.

**Comment by nicolaslopezj** [comment]
Make a pull request that merges your branch into v1.1 branch

**Comment by rwatts3** [comment]
Nick he will want to make sure he's checked out branch 1.1 to avoid
conflicts right?

On Wednesday, May 20, 2015, Nicolás López <notifications@github.com> wrote:

> Make a pull request that merges your branch into v1.1 branch
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orionjs/orion/issues/148#issuecomment-103994820>.
>


-- 
Ryan Watts
E.ryandwatts@gmail.com
C.520-442-8962
F.520-437-0914
IN. https://www.linkedin.com/in/ryandwatts

**Comment by nicolaslopezj** [comment]
Yes Ryan

**Comment by mraak** [comment]
This will still need review from someone, and a bit of guidance to finish it. Will someone check my fork once I'm done, or should I send a pull request into 1.1?

**Comment by rwatts3** [comment]
You can send PR.  Revisions and discussions will be held at the PR

On Wednesday, May 20, 2015, mraak <notifications@github.com> wrote:

> This will still need review from someone, and a bit of guidance to finish
> it. Will someone check my fork once I'm done, or should I send a pull
> request into 1.1?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orionjs/orion/issues/148#issuecomment-104000230>.
>


-- 
Ryan Watts
E.ryandwatts@gmail.com
C.520-442-8962
F.520-437-0914
IN. https://www.linkedin.com/in/ryandwatts
