### ISSUE TITLE
Adding an [Object] to a Schema

### ISSUE THREAD

**Issue by payner35** [orionjs/orion#149]
```
Events.attachSchema new SimpleSchema(
	test:
		type: [Object]
		autoform:
			item:
				type: Object
				optional: true
			"item.name":
				type: String
			"item.quantity":
				type: Number
```

Im trying to add an Object array.  But it does not seem like the autoform elements are not recognized?

![image](https://cloud.githubusercontent.com/assets/939749/7658696/4602b3de-fb4d-11e4-95e2-d09d88981680.png)

have tried "item.$.name" as well..

**Comment by timfam** [comment]
```
  item: 
    type: [Object],
    optional: true,
  ,
  "item.name":
    type: String
  ,
  "item.$.image": orion.attribute('file',
    label: 'Upload File',
    optional: true
    )
```

**Comment by payner35** [comment]
Thanks @timfam 

Heres my final working... (coffeescript)

```
Events.attachSchema new SimpleSchema(
	item:
		type: [Object]
		optional: true
	"item.$.name":
		type: String
	,
	"item.$.image": orion.attribute('file',
		label: 'Upload File'
		optional: true
	)
```

![image](https://cloud.githubusercontent.com/assets/939749/7664568/104dfe5e-fb9f-11e4-91bb-c102bd170a69.png)
