### ISSUE TITLE
Enhancement: Logging system

### ISSUE THREAD

**Issue by PEM--** [orionjs/orion#151]
Currently, Orion's logs are mixed with application logs which leads to incomprehensions from users / developers. 

I propose that we use which provides a good isolation as well as levels: https://atmospherejs.com/jag/pince.

I've used it on an app and it behaves properly with Orion separating my app logs from the one of Orion.

**Comment by timfam** [comment]
Logging is a big deal are your proposing core makes this a dependent?

**Comment by PEM--** [comment]
Yep. Currently, there `console.log` everywhere. They mix with developper's log. Thus, they can't understand if stuff is going badly owing to them or Orion.

**Comment by timfam** [comment]
Do a PR

**Comment by PEM--** [comment]
PR done #271 

:smile:
