### ISSUE TITLE
Extending config schema

### ISSUE THREAD

**Issue by ryanbuiltthat** [orionjs/orion#154]
It'd be nice if we could add default values for configuration variables. For example with the Froala config var to set the height; ideally we would set a default height that can be adjusted by a user if they need. I know we can set it within the get function:

```javascript
orion.config.get('FROALA_EDITOR_HEIGHT', 200)
```
But it doesn't appear that we can pass a default value into the configuration template. 

Other schema option I'd like to throw out there is having a config var be optional. I submitted a PR for the Froala package to add the activation key and set the editor height. If you want to set the height and don't have a key yet, you cannot save the form without a value in the activation key input field. Setting that to optional would clear that up.

**EDIT:** I had used the `{optional: true}` flag within my Froala configuration setting but that didn't seem to work. I have to test it out a little further maybe I'm mistaken. I see in other packages like S3 that there is an optional flag.

**Comment by nicolaslopezj** [comment]
Orion config is not the solution here. Config is a replacement for environment variables. 

A much simpler solution is to use nicolaslopezj:options, which is a requirement of Orion, so it's installed in all apps. 

A PR with the option to change the height using nicolaslopezj:options will be accepted.
