### ISSUE TITLE
no route

### ISSUE THREAD

**Issue by dwehrmann** [orionjs/orion#160]
Hi, 
I'm new to Orion, apologies if this is a silly question: 

After installation and starting all up, I am presented by a 
"Oops, looks like there's no route on the client or the server for url: "http://localhost:3000/."" on a blank screen. 
navigating to /admin I can create a admin user but that's all I can do here

Is this the expected behaviour or am I missing something? Do I need to create the route etc. first?

Thanks in advance
Dennis

**Comment by timfam** [comment]
Download the example app all your questions are answered in there

**Comment by dwehrmann** [comment]
@timfam Ah, I see. Thanks a lot for pointing me to the right direction.
