### ISSUE TITLE
Pages Opps message flashing up

### ISSUE THREAD

**Issue by robwatkin** [orionjs/orion#162]
I have a question about Pages.

I have implemented a simple page template pretty much exactly as suggested in the docs. It works but just after the page renders Meteor flashes up the message;

oops looks like there's no route on the client or the server for url ....

It's barely there for a tenth of a second and doesn't show up in the logs anywhere.

I suspect I'm doing something foolish. Is this a known issue? Thanks.

**Comment by rwatts3** [comment]
Can you post a screenshot of your page inside the admin panel.

**Comment by robwatkin** [comment]
I have cloned the example blog repo over at https://github.com/robwatkin/examples which demonstrates the issue. I'll just go and get some screen shots now :-)

**Comment by robwatkin** [comment]
Screen shots ...

![screen shot 2015-05-22 at 11 15 42](https://cloud.githubusercontent.com/assets/674787/7768562/5d326f1e-0074-11e5-8e08-f2b51ba43823.png)

and ...

![screen shot 2015-05-22 at 11 16 07](https://cloud.githubusercontent.com/assets/674787/7768569/73ad7400-0074-11e5-8eab-dfa0464090d2.png)

**Comment by robwatkin** [comment]
I haven't been able to fix the issue. It seems that iron-router is loading the route before the subscription is ready. I have been able to hack the pages package in order to mask the problem. My [diff](https://github.com/robwatkin/orion/commit/8401b3671778ea7f7a9de76692f9ad9941368f4c) is here

https://github.com/robwatkin/orion/commit/8401b3671778ea7f7a9de76692f9ad9941368f4c

I hope that's useful.

Thanks
Rob

**Comment by rwatts3** [comment]
Ok let me install the site really quick from your repo and see what I can discover .

**Comment by rwatts3** [comment]
Ok out of curiosity is there a reason you are forking the pages package ? , could your updates be done with a brand new package or what specifically are you updating with the core pages .

**Comment by nicolaslopezj** [comment]
This will be fixed in ```v1.1```

**Comment by robwatkin** [comment]
@rwatts3 , I was just trying to understand if I was using orion incorrectly or if there is an issue so I forked the packages so that I could feed back my experiences. I'll use the 1.1 then, presumably I need to get the latest git HEAD?

**Comment by nicolaslopezj** [comment]
The error was strange, when I was testing I saw that message for less than a second. I made some changes in the route handling, and now it works fine.

If you want to use the version 1.1 you must download the 1.1 branch and put the packages folder inside the packages folder of your app (probably you will have to create that folder).
