### ISSUE TITLE
Removing dependencies on third party UI frameworks

### ISSUE THREAD

**Issue by anthonylebrun** [orionjs/orion#166]
Because of the way meteor loads assets globally, I sort of have no choice but to use bootstrap or materialize in other parts of my app.

Could I suggest using a more lightweight, non-invasive framework like the purely semantic sass version of [Kickstart](http://getkickstart.com/)?

I'd be happy to help out with this PR if this is something you'd be interested in :) The admin interface could also use a bit of design love while we're in there :)

**Comment by nicolaslopezj** [comment]
You can create a admin interface without creating a pr. It's very easy, just follow the examples of orionjs:bootstrap and orionjs:materialize, which both are completely separate packages.

**Comment by anthonylebrun** [comment]
Ok cool, thanks for the pointer. Great project by the way :+1:

**Comment by timfam** [comment]
I look forward to your admin theme
