### ISSUE TITLE
Materialize select needs a jquery call

### ISSUE THREAD

**Issue by kbdaitch** [orionjs/orion#175]
Like so: `$('select').material_select();`

`gildaspk:autoform-materialize` package is doing that, but I don't think its templates are in use in Orion.

Any idea - what would need to be done to make select work with `orion:materialize`?

**Comment by nicolaslopezj** [comment]
Actuallly ```orion:materialize``` uses ```gildaspk:autoform-materialize```

You can't see the select?

**Comment by kbdaitch** [comment]
@nicolaslopezj yes, I cannot see with the current versions, unless I call that function in admin developer tools console.

**Comment by nicolaslopezj** [comment]
Can I see logs? photo?

**Comment by kbdaitch** [comment]
There are not much logs at all. Is there a debug mode. Anyhow, the app is pretty simple, I am just trying to learn orionjs. I shared the code with you on bitbucket, just clone and run with it. Its the `site.theme` dictionary key.

For:
```js
orion.dictionary.addDefinition('theme', 'site', {
    type: String,
    label: 'Theme',
    allowedValues: ['cyan', 'teal', 'blue']
});

orion.dictionary.addDefinition('title', 'site', {
    type: String,
    label: 'Title'
});

orion.dictionary.addDefinition('showBlog', 'site', {
    type: Boolean,
    label: 'Show Blog',
    autoform: {
        type:'switch'
    }
});
```

I get this:
![materialize_select](https://cloud.githubusercontent.com/assets/542168/7862808/4fa155fc-0526-11e5-965e-b81d52fca3bf.PNG)

**Comment by nicolaslopezj** [comment]
Try with 
```js
orion.dictionary.addDefinition('theme', 'site', {
    type: String,
    label: 'Theme',
    allowedValues: ['cyan', 'teal', 'blue'],
    autoform: {
        type:'select'
    }
});
```

**Comment by kbdaitch** [comment]
Actually tried that beforehand. No difference. I wonder if [meteor-autoform-materialize](https://github.com/djhi/meteor-autoform-materialize/) implements some types (such as `switch`) fully, while others like `select` need to be used only through templates such as `afSelect_materialize`.

**Comment by kbdaitch** [comment]
I breakpoint in [L188](`https://github.com/djhi/meteor-autoform-materialize/blob/master/materialize.coffee#L188`) but it never seems to occur.

**Comment by nicolaslopezj** [comment]
It should work. Anyway, you should open a issue on https://github.com/djhi/meteor-autoform-materialize/

**Comment by rwatts3** [comment]
Try wrapping in an afFieldInput inside autoform.

On Thursday, May 28, 2015, Nicolás López <notifications@github.com> wrote:

> It should work. Anyway, you should open a issue on
> https://github.com/djhi/meteor-autoform-materialize/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orionjs/orion/issues/175#issuecomment-106574371>.
>


-- 
Ryan Watts
E.ryandwatts@gmail.com
C.520-442-8962
F.520-437-0914
IN. https://www.linkedin.com/in/ryandwatts

**Comment by kbdaitch** [comment]
Thanks @rwatts3. Tried that as well. Not sure what the exact code path should look like, or I would have debugged more deeply. Works with bootstrap and foundation, so I am pretty sure the materialize module has some problem.

**Comment by nicolaslopezj** [comment]
I will close this because its not a orion issue
