### ISSUE TITLE
Input Type Color

### ISSUE THREAD

**Issue by raguila** [orionjs/orion#177]
I am new to Meteor so this might be a noob question. How to add input type color using the dictionary? I tried many things but I only ended up error in my Simple Schema.

**Comment by JamesLefrere** [comment]
Does something like this work?

	yourSchema = new SimpleSchema({
		yourField: {
			type: String,
			autoform: {
				type: "color"
			}
		}
	});

**Comment by raguila** [comment]
Thank you, @JamesLefrere! :) I already found the solution but didn't updated it here. My bad. But I really appreciate your answer. Cheers!
