### ISSUE TITLE
Tabular search

### ISSUE THREAD

**Issue by Deshtructioner** [orionjs/orion#203]
When I try to search for some particular content in datatable, the search doesn't really work.
To give you an example:

```js
X = new orion.collection('x', {
...
tabular: {
  columns: [
    { data: "id", title: "ID" },
    { data: "creditor", title: "Creditor", render: function (val, type, doc) {
            var x = Creditors.findOne(val);
            if(!x)
    	         return val + " not found";
            return x.name;
	  }
    },
  ]
}
```

TABLE:
ID -> 1010
C --> Tom Jones

SEARCH RESULTS:
"10" -> nothing
"1010" -> returns actual row
"Tom" --> nothing
"Tom Jones" --> nothing

So where ever I have render property, search returns nothing but also where I don't have render, search only returns result if input text is complete value, not a substring of table column content.

**Comment by nicolaslopezj** [comment]
Are you subscribed to Creditors?

**Comment by Deshtructioner** [comment]
Yes, otherwise there would be no results in datatables. Only the search doesn't work.

**Comment by nicolaslopezj** [comment]
Hm, I don't know what this could be.
You should open an issue here https://github.com/aldeed/meteor-tabular/.
