### ISSUE TITLE
Can't edit collection documents not created via CMS admin console

### ISSUE THREAD

**Issue by devillex** [orionjs/orion#209]
I have converted my Meteor collections to Orion for use with this CMS, but I have found that I can only update documents that were created via the admin interface, not ones that I have inserted through other means.

Here are two examples of entries:

**Non working; entered via application**
```json
{
	"_id" : ObjectId("5585630935f8834cf6939a59"),
	"fieldOfStudy" : "Theology",
	"fieldOfStudyId" : "Theology",
	"mappedKeywords" : [ "theology", "ministry" ] 
}
```
**Working entered via admin console**
```json
{
	"_id" : "PuS9pkZ82K5BLcYJu",
	"fieldOfStudy" : "Awesomeness",
	"fieldOfStudyId" : "Awesomeness",
	"mappedKeywords" : [ "Awesome" ],
}
```

When I click the first entry via the admin console I get a blank screen as follows:
![screenshot from 2015-06-21 13 00 49](https://cloud.githubusercontent.com/assets/11049609/8271403/06487b62-1816-11e5-9082-d5798bf763be.png)

I have no idea why one works, but the other doesn't. The only difference I can see is the value of the '_id", but I am not setting either of these manually.

For reference, here is my database schema for this collection:
```javascript
// create Orion collection to keep qualification field of study mapping
QualificationFieldOfStudyMap = new orion.collection(
  // collection name
  'qualification_fos_map',

  // collection options
  {
    singularName: 'Field of Study Entry',
    pluralName: 'Field of Study Entries',
    link: {title: 'Fields of Study'},
    tabular: {
      columns: [
        {data: 'fieldOfStudy', title: 'Field of Study'},
        {data: 'mappedKeywords', title: 'Mapped Keywords'}
      ]
    }
  }
);

// schema for the qualification field of study map
QualificationFieldOfStudySchema = new SimpleSchema({
  fieldOfStudy: {
    type: String,
    label: 'Field of Study'
  },
  fieldOfStudyId: {
    type: String,
    label: 'ID (don\'t set or update)',
    autoValue: function () {
      var fos = this.field('fieldOfStudy');
      if (fos.isSet) {
        return fos.value.replace(/\s/g, ''); // remove spaces
      } else {
        this.unset(); // prevent user from setting their own value
      }
    }
  },
  mappedKeywords: {
    type: [String],
    label: 'Mapped Keywords',
    minCount: 1
  }
})

// attach schema to collection
QualificationFieldOfStudyMap.attachSchema(QualificationFieldOfStudySchema);

// create unique index on the server collection based on the field of study id
if (Meteor.isServer) {
  QualificationFieldOfStudyMap._ensureIndex({
      fieldOfStudyId: 1
    },
    {
      unique: true
    });
}
```

Please let me know if you need any additional information.

**Comment by nicolaslopezj** [comment]
Maybe there is a SimpleSchema error. Try to run in debug mode
https://github.com/aldeed/meteor-simple-schema#debug-mode

**Comment by devillex** [comment]
I've made some progress by running all the objects in the collection through validation using:
- check(*document*, *schema*);

The error related to the '_id' field not being set. After adding this to the schema, I didn't get any validation errors, but the symptoms explained above still persist.

I attempted to enable debug mode on simple schema, but didn't get any output.

So far the only difference I can see is the '_id' values generated by SimpleSchema versus those generated by MongoDB.

**Comment by devillex** [comment]
I have instead logged an issue against [simple-schema](https://github.com/aldeed/meteor-simple-schema):
[Match error reported on '_id' field #387](https://github.com/aldeed/meteor-simple-schema/issues/387)

**Comment by devillex** [comment]
I've narrowed this down to [AutoForm](https://github.com/aldeed/meteor-autoform) expecting the '_id' of documents to be of type String, **not** Object (ObjectId).

Any idea how I can convert the '_id' values between what AutoForm requires and what MongoDB stores in the database?

**Comment by wesleyfsmith** [comment]
I thought they were all ObjectId in the DB, and in meteor they are treated like strings, so you don't need to use ObjectId? I'm not 100% clear though, because this is something that I have wondered about as well.

**Comment by devillex** [comment]
Hmm. Intersting. That would make sense, but Orion (via Simple-Schema and AutoForm) can only display documents that were created vaie the interface it seems.

Docs created using Orion use a String '_id', whereas the other documents in the collection (added with mongoimport) use ObjectId's. The latter of which can't ve displayed by Orion's individual Doc view. Both Documents (Orion and mongoimport) show up in the list view though.

I must be missing something, but can't find anything in the documentation or via Google searches yet.

**Comment by devillex** [comment]
I found the issue.

I am using mongoimport to import some collection documents. Mongoimport defaults to using ObjectID's instead of String values. This is incompatible with Meteor and Orion CMS it seems.

To fix this I manually generated String _id values in my Nodejs script that builds the JSON that I pass to mongoimport as follows:
```javascript
var ObjectID = require('mongodb').ObjectID;

// _id
var _id = (new ObjectID()).toString();
output += '"_id": "' + _id + '",';
```

**Comment by devillex** [comment]
I created a blog post that adds a little more detail on this topic: https://devillex.com/using-mongoimport-with-meteor-and-orion-cms/

**Comment by izaakhaliq** [comment]
I am stuck with this issue, but in my case, I have to be able to use ObjectID in the admin (Orion) because most data will be inserted via Robomongo. @devillex's solution only solves the issue partially, where Orion won't be using ObjectID to refer back to individual data, but falters when Admin users only need to view the data, without creating it in Orion in the first place.
