### ISSUE TITLE
Secret Keys can be queried from terminal client side

### ISSUE THREAD

**Issue by wesleyfsmith** [orionjs/orion#210]
Currently, there's nothing preventing me from calling

orion.config.get('AWS_API_SECRET') and getting the secret key. The secret key should not be able to be requested if they do not have correct privileges or if they aren't logged in.

**Comment by nicolaslopezj** [comment]
Check without been logged in with a admin account

**Comment by wesleyfsmith** [comment]
@nicolaslopezj I did, when logged out and on an incognito window they are being displayed when they shouldn't.

**Comment by wesleyfsmith** [comment]
I fixed it in this PR https://github.com/orionjs/orion/pull/211

**Comment by wesleyfsmith** [comment]
It was an issue with the fields query where it was including non public fields.

**Comment by nicolaslopezj** [comment]
Wow, this is a big bug. I will update immediately

**Comment by wesleyfsmith** [comment]
Hey @nicolaslopezj, there was actually a bug in my fix that will cause mongo to error out if you mix public and private keys. This PR https://github.com/orionjs/orion/pull/212 fixes that problem, let me know if you have questions.

**Comment by nicolaslopezj** [comment]
Don't worry, I fixed it.

**Comment by wesleyfsmith** [comment]
Awesome, nice catch.
