### ISSUE TITLE
Sensitive data exposed?

### ISSUE THREAD

**Issue by lhristov** [orionjs/orion#214]
Hi,
first, thank you for the great product.
I was testing with Google Webmaster tools and I noticed that all my sensitive data in orion.config is available to the world without restrictions.

See attached.

![orion_config](https://cloud.githubusercontent.com/assets/2388703/8399234/aab672dc-1dd7-11e5-8db1-c18ca65756e1.png)

Can you confirm this? I removed all SEO packages that could have exposed this, but I verified with the code and I think it's not a fluke, but "by design".

**Comment by lhristov** [comment]
It seems the **orionjs:config** package that is normally pulled is outdated.
When I explicitly installed the package, it updated to 1.1.2 and now the data is safe.
FYI:
1. My list **before** the update:
```orionjs:filesystem       1.1.0  Orion Filesystem```
```orionjs:image-attribute  1.1.4  Image attribute for orion```
```orionjs:materialize      1.1.7  Materialize theme for orion admin```
```orionjs:relationships    1.1.2  Define and use relationships between meteor collections, entities and the dictionary```
```orionjs:s3               1.1.0  S3 storage for orion:filesystem```
```orionjs:summernote       1.1.0  Summernote editor for orion```
2. **After** the update:
```orionjs:config           1.1.2  Orion Filesystem```
```orionjs:filesystem       1.1.0  Orion Filesystem```
```orionjs:image-attribute  1.1.4  Image attribute for orion```
```orionjs:materialize      1.1.7  Materialize theme for orion admin```
```orionjs:relationships    1.1.2  Define and use relationships between meteor collections, entities and the dictionary```
```orionjs:s3               1.1.0  S3 storage for orion:filesystem```
```orionjs:summernote       1.1.0  Summernote editor for orion```

I hope this helps.

**Comment by frabrunelle** [comment]
Yes, this was reported a few days ago and promptly fixed. See https://github.com/orionjs/orion/issues/210.

**Comment by lhristov** [comment]
@frabrunelle - thank you for your quick reply.
To help other users:

1. They should make sure they install ```orionjs:config``` explicitly
2. I'm not an expert, just a suggestion: perhaps you should fix the version dependencies of the other packages so people who do not see this thread won't have this issue anymore.

Again, thank you guys for sharing this awesome framework!
