### ISSUE TITLE
Dictionary migrations

### ISSUE THREAD

**Issue by Deshtructioner** [orionjs/orion#216]
Is there a way to migrate data to dictionary too? Before I reset my meteor project, I ran mongoDB, command: "db.dictionary.find()" and copy&paste output to txt file. Then I reset my project (data was deleted) and now, I want to migrate that copied output back to project, instead of writing same definitions over and over again when I reset project?

Dictionary.insert...returns error (Dictionary is not defined)

**Comment by PEM--** [comment]
Dictionary is a collection with a single entry. You can populate it either by using `defaultValue` like so:
```coffee
# Stop subscription
orion.dictionary.addDefinition 'endSubscription', 'settings',
  type: Boolean, label: 'Stop subscriptions'
  defaultValue: false
```

Or, server side only, by directly taping into the collection like so:
```coffee
if Meteor.isServer
  dicId = (orion.dictionary.findOne())._id
  orion.dictionary.update dicId, {'$set': headValues} , (err) ->
    return appLog.error "Dictionnary update failed: #{err}" if err
    appLog.info 'Default site description created or updated'
```
