### ISSUE TITLE
"Add Account" button is not rendered correctly

### ISSUE THREAD

**Issue by ffxsam** [orionjs/orion#219]
On a fresh install of Orion:

![page_title](https://cloud.githubusercontent.com/assets/12532733/8502450/e49a1770-2164-11e5-90f2-606c8c9785e8.png)

**Comment by ffxsam** [comment]
Using twbs:bootstrap and orionjs:bootstrap packages.

**Comment by frabrunelle** [comment]
You need to add Font Awesome manually.

`meteor add fortawesome:fontawesome`

here is the answer from @nicolaslopezj:

> But as bootstrap, people need to see choose which version of font awesome they want to load, cnd or server the fonts themselves. That's why it's not a dependency.

> But we need to say that it need to be installed in the docs

As he said, we should clarify the docs to mention the Font Awesome needs to be installed. I'll see if I can do a PR.
