### ISSUE TITLE
Is it possible to upload files into filesystem

### ISSUE THREAD

**Issue by chompomonim** [orionjs/orion#225]
As far as I understand you support only saving files into S3. How about local filesystem and/or GridFS?

**Comment by timfam** [comment]
http://orionjs.org/docs/introduction and we also have a forum http://forums.orionjs.org/

**Comment by chompomonim** [comment]
@timfam thanks for links. I found a few packages: 
 - https://github.com/brightbind/orion-gridFS
 - https://github.com/vsivsi/orion-file-collection

Both are working well.

P.S. I think you should delete `lc3t35:orion-filesystem-local` from your introduction as it show an error for now:

> jaro$ meteor add lc3t35:orion-filesystem-local
> => Errors while parsing arguments:
> While adding package lc3t35:orion-filesystem-local:
> error: no such package
