### ISSUE TITLE
orion unstyled version

### ISSUE THREAD

**Issue by amazingBastard** [orionjs/orion#226]
Is it possible to get an unstyled version of the package same as useraccounts:unstyled does? I don't really like using bootstrap and don't want to load bootstrap dependencies just for the admin dashboard to work. Any chance of this happening in the future? Thanks

**Comment by kevohagan** [comment]
it's quite easy to do it yourself. just copy the boostrap or materialize admin package and adapt it to your needs ;).

**Comment by amazingBastard** [comment]
Cool, I'll take a look and hopefully do a PR for it.

**Comment by nicolaslopezj** [comment]
@amazingBastard If you make a package publish it as yours and we will add it to the list of contributions!
Thanks!

**Comment by amazingBastard** [comment]
Hey, so I've been working on unstyling the boostrap package. I'm pretty much ready to publish but I'm running into this strange issue:

lib/views/accounts/update.html:60: Unexpected closing template tag
...      {{/ autoForm }}     </div>      <h2...

I don't know why this comes up since I'm using the exact same template, just changing the class names. I don't know what it's complaining about as I can't find any missed closing tags. Any ideas on this? Thanks.

**Comment by kevohagan** [comment]
there is obviously some kind of typo or missing html tag somewhere in that
file.

do you have a repo for us to look at?

**Comment by amazingBastard** [comment]
Hey this is the file here: https://github.com/amazingBastard/orion-unstyled/blob/master/lib/views/accounts/update.html

**Comment by amazingBastard** [comment]
Hey,

So I managed to publish the package but I noticed some bugs. I cleaned up the issues but I have no idea how to actually update the published package.

I tried running meteor publish --update but the package isn't updated. Any thoughts on this? Thanks.

**Comment by amazingBastard** [comment]
Ok, sorry for the constant comments.

I think I got it figured out. For anyone that needs the solution, what I did was:

update the version number in package.js and then I simply ran meteor publish to publish the updated version. Then you have to run meteor update in your app.

I'm working out the kinks but the package is mostly working now if you want to add it to the docs. Here's the package:

https://atmospherejs.com/dvz/orion-unstyled
