### ISSUE TITLE
Pages URL not unique

### ISSUE THREAD

**Issue by Aselox** [orionjs/orion#229]
Even if in the packages/pages/pages.js file the url filed is defined unique in the schema, it's not validated while creating a new page. This could be due the fact that url must be set as index according to the [collections2 documentation](https://github.com/aldeed/meteor-collection2#index-and-unique).

I tried forking the repo and adding `index: true` but it still doesn't validate the url filed for uniqueness. I think this could be due the fact that the schema for the pages collection is "extended" with user custom fields and this could cause SimpleSchema to malfunction.
Any thoughts?

**Comment by nicolaslopezj** [comment]
When you set unique in the schema it sets a unique index in the database. You can't inset 2 documents with the same url

**Comment by Aselox** [comment]
@nicolaslopezj Yes, this works with an orion.collection with `unique: true` defined in the schema but with pages from the pages package it seems I can have pages with the same url without.

**Comment by nicolaslopezj** [comment]
Hm.. orion.collections and pages are both Mongo.Collections.
It should work, try doing a meteor reset

**Comment by Aselox** [comment]
@nicolaslopezj I did a meteor reset and it still lets me create pages with the same link
![image](http://i.imgur.com/4I7qZvF.png)
I also tried on a new meteor app with no files (except for pages templates) and it still lets me create pages with the same link.

**Comment by nicolaslopezj** [comment]
You are right.

**Comment by nicolaslopezj** [comment]
This will not allow to have equals urls, but pages need api changes to show the unique error message  when inserting.

**Comment by rwatts3** [comment]
It's the page title that is validated against unique not the link itself.  We should handle this so that both values must be unique.  We should also account for if a link is not added then the page title will be converted into s friendly URL

**Comment by kevohagan** [comment]
we could do an dynamic auto-suggestion of the slug when you first enter the
title too
