### ISSUE TITLE
Seeding dictionary with defaultValue to avoid empty initial fields in admin interface

### ISSUE THREAD

**Issue by semikolon** [orionjs/orion#23]
Dictionary entries should be seeded (database prepopulated), I felt. This way, the admin users won't be met with empty fields when first using the admin interface. Having an empty field there meant they'd have to go to the home page, copy the HTML of the field in question, paste it in admin and tweak it from there.

Seeding the defaultValue from the dict_seed helper makes the first-ever edit of a dictionary field smoother for the admins.

This might not be for everybody, and there certainly might be a more elegant solution. A major drawback of this solution is that A) the site needs to be visited in order for the value to be seeded (because dict_seed needs to run for every dictionary entry), and B) that there might be a performance hit when running the template helper.

```coffee
if Meteor.isClient
  Template.registerHelper "dict_seed", (name, seedValue) ->
    if orion.dictionary.get(name) is '' and seedValue
      dictionary_id = orion.dictionary.collection.findOne()?._id
      if dictionary_id
        to_set = {}
        to_set[name] = seedValue
        orion.dictionary.collection.update(dictionary_id, $set: to_set)
        log "Reset dictionary definition value for #{name} to seedValue"
    orion.dictionary.get(name)
```
For reference, this is the original `dict` helper:
```js
Template.registerHelper('dict', function(name, defaultValue) {
	return orion.dictionary.get(name, defaultValue);
});
```

**Comment by nicolaslopezj** [comment]
@semikolon I think this is a great idea, but not everyone prefer this. We should leave the option for the developer. I you could make a package it would be great!

**Comment by timfam** [comment]
@semikolon what we need is an adaption of dburles:factory and anti:fake (use this fork https://github.com/pociej/meteor-fake) for seeding data into Orion. This is a more general solution.

**Comment by rwatts3** [comment]
Why not just set a conditional on the dictionary.  Then set the dictionaries value in the code.  The conditional can check if the dictionary currently has a value.  If it doesn't then it will set the value.

**Comment by rwatts3** [comment]
The dictionary comes with a better and a setter.

**Comment by timfam** [comment]
You are right. I was speaking generically,  maybe useful to orion is a
seeder for various content. Factory does a good job of that.

**Comment by rwatts3** [comment]
Also a side note.  But I have been using placeholders.  To as a memo or example of what content can go into the newly created dictionary.  I know this is desperate from the original question.  But thought it would be helpful.

**Comment by rwatts3** [comment]
Another note.  I got tool tips to work with autoform.  I am writing a tutorial on how to add and use tool tips.

**Comment by nicolaslopezj** [comment]
That's great @rwatts3

**Comment by rwatts3** [comment]
Ps sorry for the typos.  Typing from iPhone doesn't work as well.

**Comment by timfam** [comment]
Awesome!

**Comment by timfam** [comment]
Welcome to the club of mobile phone editing lol. In same both.

**Comment by timfam** [comment]
Updated tutorial with howto seed content

**Comment by rwatts3** [comment]
Nice @timfam
