### ISSUE TITLE
Dictionary defaultValue doesn't work

### ISSUE THREAD

**Issue by Aselox** [orionjs/orion#230]
As reported in the [forums](http://forums.orionjs.org/t/seed-dictionary/44/4?u=aselox) the `defaultValue` parameter doesn't set a default value for the dictionary entry.
Here is the code I used to confirm this:

```javascript
orion.dictionary.addDefinition("elevatedVery", 'charts.depression', 
    {
        type: String,
        label: "Very Elevated",
        defaultValue: "Feeling good"
    }
);
```

The field is empty instead of having the "Feeling good" value.

**Comment by nicolaslopezj** [comment]
That will not work, I will explain why:

The defaultValue key in the schema indicates that when a new document its created, if the field is not set, it will take that value.
The dictionary collection has always one document, you can't insert or remove it, just update it.

**Comment by timfam** [comment]
@Aselox My bad I over looked that - dictionary are getter and settter

**Comment by Aselox** [comment]
@nicolaslopezj oh ok, so is there a way to set a default value for a dictionary entry?

**Comment by nicolaslopezj** [comment]
Not a official way now, but it could be a future feature

**Comment by nicolaslopezj** [comment]
Ready for 1.2
