### ISSUE TITLE
Orion user profile

### ISSUE THREAD

**Issue by Ajaxsoap** [orionjs/orion#237]
Hi,

Thank you so much for making Orion!

I would like to ask if how do I configure user profile onCreateUser form? Is it the same approach on the main meteor <a href="https://github.com/meteor-useraccounts/core/blob/master/Guide.md">useraccounts</a> package? 

I've used materialize:materialize, orionjs:materialize package and i want to extend the user profile. ex. Company, Branch, Username etc.

I already set a custom user roles the orion way :)

I've read the documentation and nothing explains how to do this kind of stuff? Is there an Orion way to do this?

Thanks,

Marvin

**Comment by nicolaslopezj** [comment]
You can check here
http://forums.orionjs.org/t/extra-fields-in-registration-form/59

**Comment by Ajaxsoap** [comment]
Thanks so much Nicolas!\

Cheers!
