### ISSUE TITLE
Wrong default value for dictionary entry as Boolean

### ISSUE THREAD

**Issue by PEM--** [orionjs/orion#240]
Dictionary entry as Boolean are either `true` or `""` (an empty String).

Even if we use a `defaultValue` in the entry declaration as `false`.

**Comment by nicolaslopezj** [comment]
Please explain more

**Comment by PEM--** [comment]
Boolean should be either true or false. Not an empty string.

**Comment by nicolaslopezj** [comment]
Hm, that seems like a issue with SimpleSchema/Autoform or no?

**Comment by PEM--** [comment]
Sounds more related to the treatment of default value in the dictionary package https://github.com/orionjs/orion/blob/master/packages/dictionary/dictionary.js#L100

**Comment by nicolaslopezj** [comment]
So you are doing
```js
orion.dictionary.get('my.definition', false);
```
And it returns a empty string?

Sorry, it is still not clear for me

**Comment by PEM--** [comment]
No problem, my friend. I was on my phone. I've just switched.

In the documentation, we are stating that we can define a dictionary entry like so:
```js
orion.dictionary.addDefinition('description', 'site', {
    type: String,
    label: 'Description',
    defaultValue: 'My description'
});
```

Thus, if we are using a `Boolean` instead of a `String`, for a behavioral flag for instance, we could write it this way:
```js
orion.dictionary.addDefinition('flags', 'somecategory', {
    type: Boolean,
    label: 'Behavior',
    defaultValue: false
}); 
```

When using it this way, we get an empty `String` instead of the `defaultValue` set to `false`:
```js
orion.dictionary.get('somecategory.flags')
```

Inherently, in our admin interface, an empty `String` is always `false` leading to an UI with a checkbox that you can't set properly, and in the code that uses such value, you end up with a wrong type.

**Comment by nicolaslopezj** [comment]
Fixed with ```orionjs:dictionary@1.2.2```

**Comment by nicolaslopezj** [comment]
From ```orionjs:dictionary@1.2.3``` the default defaultValue will be ```undefined``` instead of an empty string.

**Comment by PEM--** [comment]
:+1: Thanks.
