### ISSUE TITLE
I'm starting a comprehensive tutorial based on Microscope.

### ISSUE THREAD

**Issue by fuzzybabybunny** [orionjs/orion#244]
Here:

https://github.com/fuzzybabybunny/microscope-orionjs

**Comment by fuzzybabybunny** [comment]
Updated with a section on the Dictionary:

https://github.com/fuzzybabybunny/microscope-orionjs#dictionary-updated-7282015

**Comment by jorisroling** [comment]
Very nice! Keep up that good work...

**Comment by nicolaslopezj** [comment]
Great! thanks for contributing!

**Comment by fuzzybabybunny** [comment]
@nicolaslopezj, thanks for the kudos! Is there something I should do to make this tutorial easier to find for people? I think there's been some interest in the past for a tutorial like this that takes people through an entire project.

**Comment by nicolaslopezj** [comment]
I will add it to the website

**Comment by nicolaslopezj** [comment]
https://github.com/orionjs/tutorials/blob/master/tutorials/microscope.md
http://orionjs.org/tutorials/microscope
