### ISSUE TITLE
How do you subscribe to additional data in the admin panel?

### ISSUE THREAD

**Issue by fuzzybabybunny** [orionjs/orion#246]
I've got a `Posts` collection and a `Comments` collection.

When I go into the `Comments` section of OrionJS I can see a table with the comment's `authorId`, `postId`, etc. I want to replace the IDs with the actual name of the author and the title of the post, but that requires me to subscribe to part of the Posts and Users collections. 

The only collection I'm subscribed to when inside the `Comments` section is the Comments collection.

How do I subscribe to additional collections? Is there some sort of hook or value I can pass into some kind of config setting?

I can probably hack it with some kind of template-level subscription but that just feels... dirty.

**Comment by nicolaslopezj** [comment]
I think the best way to do that right know is:

```js
ReactiveTemplates.onCreated('collections.comments.index', function() {
  this.subscribe('myPublication')
});
```

**Comment by fuzzybabybunny** [comment]
Thanks. Template-level subscriptions it is. I've added a whole new section of custom templates to the tutorial:

https://github.com/fuzzybabybunny/microscope-orionjs#changing-tabular-templates-updated-7292015
