### ISSUE TITLE
Flow-Router - any plans to switch or support the new router?

### ISSUE THREAD

**Issue by dalerka** [orionjs/orion#248]
Hey guys, huge thanks for your hard work! 
Are there any plans to switch to FR?
What are the main roadblocks and concerns here?
Or would it be possible to make *OrionJS* router-agnostic somehow?
Yet, it would be ugly to have two routers in the app, because some of the packages still depend on IR, so any comments and suggestions about this?

**Comment by amazingBastard** [comment]
+1, would love to see orion decoupled from iron:router somehow.

**Comment by nicolaslopezj** [comment]
I want to make this but it is very difficult.

To do this we must create a router layer that accepts iron router and flow router.

**Comment by dalerka** [comment]
Great! So, what would be some possible ways/steps to implement the router layer? i.e. 
1. move all subscriptions to *Templates*?
2. create an *Orion-Router* object [or a stand-alone *Router-connector* package] which would accept routing requests from *Orion-core* and *plugins* (other packages)?
3. *Orion-Router* could check if *FR* is available and if not fall back to *IR* as dependency?
4. *Orion-Router* will pass the routing calls to a selected router?
5. the docs should explicitly tell the developer to install *FR* if they want to. 
6. but some packages need to switch to use the *Router-connector* package too, otherwise we'll end up with two routers in one app and possible route-name clashes? no?

What do you think guys?

**Comment by Ajaxsoap** [comment]
+1

**Comment by amazingBastard** [comment]
@dalerka I think you're on point about creating a router package for orion that will check which router app has installed and use that. Seems like a challenge to do though, I'd be willing to help where I can.

**Comment by dalerka** [comment]
@amazingBastard, thanks! I also think there could be a stand-alone package like *Router-layer* to be used in any Meteor app/package as middleware, so people can have more flexibility, but:  
A) what exactly would be the most challenging things in building such a package?  
B) what would be the easiest parts?  
C) what are the things to keep in mind?

**Comment by nicolaslopezj** [comment]
I think the router layer should support only the basics.

Setting the route template and a layout. Also a way to check which is the active route.

Router layer will be used by packages and the use should be very basic. The app will have all features that each router has.

**Comment by nicolaslopezj** [comment]
I started a router-layer project

https://github.com/nicolaslopezj/meteor-router-layer

**Comment by nicolaslopezj** [comment]
Also pages needs changes

**Comment by nicolaslopezj** [comment]
Ready with 1.4
