### ISSUE TITLE
Possible to integrate with cfs:s3?

### ISSUE THREAD

**Issue by fuzzybabybunny** [orionjs/orion#251]
I prefer to use [cfs:s3](https://github.com/CollectionFS/Meteor-CollectionFS/tree/devel/packages/s3) because it offers more features than the other s3 package from Orion. In my case I really require the `beforeWrite`, `transformWrite`, `transformRead`, etc methods that are available to modify image files with `ImageMagick`. It also deletes the image stored in S3 when you do something like 

```javascript
Images.findOne().remove(function(error, success){
  console.log(success)
});
```

**Comment by nicolaslopezj** [comment]
Yes you can.

Look the s3 package and make it fit for you.

You can also read here

#8
