### ISSUE TITLE
Tabular Data table - TableTools extension is not exporting orion.attributeColumn

### ISSUE THREAD

**Issue by Ajaxsoap** [orionjs/orion#253]
Hi,

I've managed the [TableTools](https://www.datatables.net/extensions/tabletools/) extension to work on my app but the  problem is all **orion.attributeColumn** is not inlcuded during export,

Here's my tabular schema:
```
  Claim = new orion.collection('claims', {
      singularName: 'claim',
      pluralName: 'claims',
      link: {
        title: 'Claims'
      },
      tabular: {
        dom: 'T<"clear">lfrtip<"clear">R<"clear">C',
        tableTools: {
                  "sRowSelect": "multi",
                  "aButtons": [ "copy", "csv", "xls", "pdf", "print" ],
                  "sSwfPath": "/swf/copy_csv_xls_pdf.swf"
                },
        columns: [
          {data: "enrollmentId", title: "Claimant"},
          {data:"status", title: "Status"},
          {data:"fileAttachments", title:"Attachments"},
          orion.attributeColumn('createdBy', 'createdBy', 'Created By'),
          {
            tmpl: Meteor.isClient && Template.myData
          }
        ]
      }
    });
```

Here's my button template:
```
    <template name="myData">
      <button type="button" class="btn btn-xs">Select</button>
    </template>
```
Screenshot of my table with selected rows, ~~this is because for the extension to work, the rows that you want to export or print or whatever should selected based on <a href="https://github.com/aldeed/meteor-tabular#integrating-datatables-extensions">tabular data table extension guide</a>~~, **I tested not to select any rows and the exported file is exporting all rows**.

![image](http://forums.orionjs.org/uploads/default/33/950d75e04dfa427b.jpg)

the exported pdf file from the selected rows: [link to pdf][1]
  [1]: https://drive.google.com/file/d/0B8Y0IkeLiEtgaUdOM0VieVpYWTg/view?usp=sharing

Notice the **createdBy** orion.attributeColumn is empty on pdf.

**Comment by nicolaslopezj** [comment]
Maybe its because it uses publications.
Use a custom publication that includes the users collection for this tabular table.

**Comment by Ajaxsoap** [comment]
Even in my other collections, **createdAt** orion.attribute is not being exported.

**Comment by Ajaxsoap** [comment]
Is there any workaround on this issue? 

I tried the normal date type not using orion.attributeColumn :( but the format is not so pleasing, however, it is included on the exported field. 

I like the features of **orion.attribute** a lot but this issue is somewhat disheartening for me as I want also the capabilities of Table Tools extension. I'm in a dead end here :(

Any help is deeply appreciated!

**Comment by nicolaslopezj** [comment]
The problem is that the publish function of your tabular does not subscribe to the users collection, that is done on the createdBy template.

You must create a custom publish function for your table

**Comment by Ajaxsoap** [comment]
Actually, the behaviour is not on the **createdBy** user alone, all the orion.attributeColumn **createdAt**, relationship **hasOne** and **hasMany** is not being exported but if I use a normal schema the fields is included on exported file. I don't know how to troubleshoot this but maybe the way orion.attribute transform or function is causing the issue?

**Comment by nicolaslopezj** [comment]
You can use orion attributes and define the columns yourself.

```js
Claim = new orion.collection('claims', {
      singularName: 'claim',
      pluralName: 'claims',
      link: {
        title: 'Claims'
      },
      tabular: {
        dom: 'T<"clear">lfrtip<"clear">R<"clear">C',
        tableTools: {
                  "sRowSelect": "multi",
                  "aButtons": [ "copy", "csv", "xls", "pdf", "print" ],
                  "sSwfPath": "/swf/copy_csv_xls_pdf.swf"
                },
        columns: [
          {data: "enrollmentId", title: "Claimant"},
          {data:"status", title: "Status"},
          {data:"fileAttachments", title:"Attachments"},
          {data:"createdBy", title:"Created By"},
          {
            tmpl: Meteor.isClient && Template.myData
          }
        ]
      }
    });
```
