### ISSUE TITLE
Accounts index not displaying all non-admin roles after updating orion to 1.3.0

### ISSUE THREAD

**Issue by Ajaxsoap** [orionjs/orion#255]
After updating Orion 1.3.0, on the accounts index page, all the non-admin roles is not showing on he table, see image below:

![accounts](https://cloud.githubusercontent.com/assets/6571832/9150677/e2788014-3e18-11e5-8324-bf06228bd41d.jpg)

Is this normal behaviour for version 1.3.0?

**Comment by PEM--** [comment]
Same issue, there.

**Comment by PEM--** [comment]
#257 fixes the issue.

**Comment by nicolaslopezj** [comment]
Thanks @PEM--
