### ISSUE TITLE
Is it possible to use other relationship package in orion?

### ISSUE THREAD

**Issue by Ajaxsoap** [orionjs/orion#258]
Hi,
I am wondering if possible in orion to use other relationship package other than orion:relationship? 

Thanks,

**Comment by nicolaslopezj** [comment]
It should be posible, which package do you refer?

**Comment by Ajaxsoap** [comment]
I see that [meteor-joins](https://github.com/perak/meteor-joins) is the package that will solve my problem in joinng two collections. In orion relationship only one field is passed from other collections **hasOne**, in meteor-joins you can specify which fields you want to pass, even all the fields from other documents(_id), it would be great if orion relationship will extend to this capability to lessen package dependency. Or am i missing something or not fully understood the true capability of orion relationship? 

I filed an issue a month ago on their repo [#1](https://github.com/perak/meteor-joins/issues/1)
I have a scenario, I have two collections. 
enrollments collection
claims collection

I have enrollees list in enrollments collection. 
How do I pass a certain or all fields from enrollments collection to claims collection with additional fields? 

Example
<strong>Enrollments collection</strong>
<table>
<thead><tr><th>Name</th><th>Birthdate</th><th>Status</th><th></th></tr></thead>
<tbody>
<tr>
<td>John</td>
<td>02/02/1990</td>
<td>Single</td>
<td>Claim me!</td>
</tr>
<tr>
<td>Peter</td>
<td>02/02/1980</td>
<td>Married</td>
<td>Claim me!</td>
</tr>
</tbody>
</table>

Let say i placed a claims button (Claim me!) per enrollee in the list, then if I click it, it will route me to add claims, wherein the fields from that particular enrollee will be carried/passed it over plus additional fields(amount,dateofClaims) to the claims collection upon clicking the submit button.<br>

Voila! Claims list.

<strong>Claims collection</strong>
<table>
<thead><tr><th>Name</th><th>Birthdate</th><th>Status</th><th>Claims Amount</th><th>Date Claimed</th></tr></thead>
<tbody>
<tr>
<td>John</td>
<td>02/02/1990</td>
<td>Single</td>
<td>$500</td>
<td>06/06/2015</td>
</tr>
</tbody>
</table>

How i will relate this in orion way?

Thanks.

**Comment by nicolaslopezj** [comment]
Orion is unobtrusive, you can do it the same way you would do it without Orion.

Where are you having problems?

**Comment by Ajaxsoap** [comment]
If I use the **hasOne** relationship and I want to get all the fields from other collections, currently, it is not possible in orion? Probably, you may extend the functionality of relationship in future release?

**Comment by nicolaslopezj** [comment]
Currently that is not posible.
But you could do it yourself using https://atmospherejs.com/matb33/collection-hooks

**Comment by Ajaxsoap** [comment]
Thanks Nicolas! 

I believe that Orion has a bright future ahead!

**Comment by nicolaslopezj** [comment]
Lets leave it closed
