### ISSUE TITLE
Extending/miniaturise Orion export/import on tabular table level

### ISSUE THREAD

**Issue by Ajaxsoap** [orionjs/orion#261]
Hi,

I am wondering if possible to extend/miniaturise the functionality of export/import package on a tabular level? Currently, the functionality of it is for all collections and dictionary. It would be great if we can import a csv file on a table and not removing the existing data, instead it will append on the table. I have a test repo demo about [csv import](https://github.com/Ajaxsoap/meteor-sample-csv-importer) but i don't think it will run on orion, I didn't test it yet.

**Comment by nicolaslopezj** [comment]
I don't think that feature would be in the near future, but I have done that in the past and you could use it as example. It was a older orion version, the only change is the way of creating admin links.

The code that receives the upload
https://github.com/madeby-nicolaslopezj/asistencias-uai/blob/master/server/upload.js

Templates of the upload view
https://github.com/madeby-nicolaslopezj/asistencias-uai/tree/master/client/views/upload

Library that I used (I were using xlxs, not csv)
https://github.com/madeby-nicolaslopezj/asistencias-uai/blob/master/client/compatibility/excel.js

Any question you can ask

**Comment by Ajaxsoap** [comment]
Thanks Nicolas! :+1: 

I can see that on the template who loads all the data from xlxs is not a table,  instead it will create a spreadsheet like excel UI just like in sheet js demo? and the current version of orion is using autoform and tabular which i think will conflict, that's why this feature is excluded on the future of orion. Maybe, if i could use it on my project and I will figured out how I will integrate this with my current setup of orion. 

What do you think @nicolaslopezj  should l go for it? :)

**Comment by nicolaslopezj** [comment]
Yes! go for it.
Share your results

**Comment by Ajaxsoap** [comment]
Yeah!

Thanks @nicolaslopezj!
