### ISSUE TITLE
Latest update breaks admin routing

### ISSUE THREAD

**Issue by amazingBastard** [orionjs/orion#262]
So I noticed the latest version broke the admin routes. For example, I can only navigate to the last collection that was loaded, all other routes although update in the URL correctly do not load the proper templates belonging to that collection. Maybe this has something to do with the new router-layer? Just checking to see if anyone else has this problem.

**Comment by frabrunelle** [comment]
I've also been experiencing this problem when I tried to upgrade to the latest version of Orion.

**Comment by nicolaslopezj** [comment]
It was a difficult to find bug that was caused because all collections templates were the same and the code was written if they were all different
