### ISSUE TITLE
issue with RouterLayer.getPath()

### ISSUE THREAD

**Issue by payner35** [orionjs/orion#266]
RouterLayer.getPath() is always null for me and causing an issue...

![image](https://cloud.githubusercontent.com/assets/939749/9252588/2ff64680-41ea-11e5-9d5f-eaaa27c06a6f.png)

I suspect this is to do with the recent update to the "update router layer version"

https://github.com/orionjs/orion/commit/d7b5207b4790c1b09545c50e7a26a40156fec7a3

**Comment by nicolaslopezj** [comment]
Confirm that you are using the latest versions:

orionjs:base@1.4.1
orionjs:collections@1.4.1
nicolaslopezj:router-layer@0.0.8

Are you using iron router or flow router?

I'm not having this issue :/

**Comment by payner35** [comment]
I have done a meteor update to get the latest packages..

using iron-router

have set up a smaller project to help diagnose the issue.. here are my packages

meteor-platform
orionjs:core
orionjs:froala
coffeescript
orionjs:file-attribute
orionjs:image-attribute
orionjs:s3
jquery
stylus
underscore
orionjs:relationships
iron:router
twbs:bootstrap
fortawesome:fontawesome
orionjs:bootstrap
useraccounts:iron-routing

**Comment by payner35** [comment]
great... thanks.
