### ISSUE TITLE
Collection view is not re-rendered when selecting different collection menu items

### ISSUE THREAD

**Issue by alduethadyn** [orionjs/orion#273]
After upgrading to 1.4.0 of the orionjs packages, my navigation seems to be broken when moving between collection pages. 

I am developing on a Mac with OS X Yosemite (10.10.4), Chrome (44.0.2403.130 (64-bit)) - there are no errors in the logs or console in the browser.

Sample project demonstrating the issue: https://github.com/alduethadyn/orionjs-collection-navigation-issue 

**Steps to recreate bug:**

1. `meteor create navigation-bug`
2. `cd navigation-bug`
3. `meteor add orionjs:core orionjs:froala orionjs:pages orionjs:accounts orionjs:relationships orionjs:bootstrap twbs:bootstrap fortawesome:fontawesome orionjs:filesystem orionjs:file-attribute orionjs:image-attribute kadira:flow-router kadira:blaze-layout coffeescript less`\*
4. Add Orion collection definitions for Products, Plans, Units and some attributes/columns (see git repo)
5. Add a simple redirect using FlowRouter from '/' to '/admin'
6. Add a simple layout.html (mimicking my normal layout for a project)
7. `meteor`
8. navigate to localhost:3000/admin (or localhost:3000/ obviously)

\**created with the same packages used in my real project*

**Try the following in the running app:**
- click between Products, Plans, and Units that have *different* column names/attribute-types, and observe that the columns don't change
- click on menu items added by official orionjs packages, like Config or Pages, and click back to a collection menu item and the correct table information is shown. 
- click on two different collections in order, e.g. Products, then Plans, click the plus icon and note that the *correct* create form is displayed. 

Is this happening for anyone else after the update to 1.4.0?

**Comment by PEM--** [comment]
Same issue here since 1.4.
