### ISSUE TITLE
Introduction incomplete

### ISSUE THREAD

**Issue by sean-stanley** [orionjs/orion#280]
Hi,

Orion sounds awesome and I'd like to try it out. Especially since I am starting a new project with Flow Router. However, I am not sure what to do after following all the instructions in the introduction. I am told to go to localhost:3000/admin but I have not setup any routes for that and when I try I am redirected to /admin/my-account and get errors saying the template is undefined.

Should I create a user first? Any tips for continueing getting started would be appreciated.

**Comment by nicolaslopezj** [comment]
Please ask in the [forums](http://forums.orionjs.org)!

**Comment by sean-stanley** [comment]
Thanks for the tip about the forums. I found a link to a tutorial on using the latest Orion Js with Microscope but it would be nice to learn more about specific requirements when setting up from scratch. Do I need to predefine some particular routes, add admin roles manually, etc.

**Comment by nicolaslopezj** [comment]
There was a error with materialize, not it should work

**Comment by sean-stanley** [comment]
Works great. Thanks!  

--  
Sean Stanley

**Comment by sean-stanley** [comment]
Hello,
Isn't it the information you were looking for? Read about it here <http://vyfechunge.vjron.com/lnncbmmd>

Hope this helps, Sean Stanley

**Comment by sean-stanley** [comment]
Hey,

Just look at that interesting stuff, I love it! I think you're gonna like it too, take a look here <http://nguhefosu.juliemillerlaw.com/lnwjje>

Good wishes, Sean Stanley
