### ISSUE TITLE
What is the behaviour of adminLinks (sidebar) when it comes to positioning? 

### ISSUE THREAD

**Issue by Ajaxsoap** [orionjs/orion#281]
Hello,
I would like to ask if what is the behaviour of the sidebar when it comes to positioning of individual  links?

Is there a way or is it possible to reorder the links the way I want to? 

Thanks,

**Comment by PEM--** [comment]
The sidebar is populated by **orionjs:collection** when you create your collections. It preserves the order that you've defined in your sources.

Simply put. By re-odering your code, you can re-order the sidebar.

**Comment by nicolaslopezj** [comment]
Links are saved in a local collection, so you can update the index of a link.

```js
orion.links._collection.update({ identifier: 'collections-myCollection' }, { $set: { index: 1 } });
```

**Comment by PEM--** [comment]
Smart. Yummy!

**Comment by Ajaxsoap** [comment]
Hi @PEM-- I tried your suggestion but the relationship is broken:

I have this
```
mycollection-top "hasMany" relationship with myCollection-bottom
```
the issue here is that myCollection-bottom is not defined. It should be myCollection-bottom is on top of myCollection-top. 

Hi @nicolaslopezj , I also tried your suggestion but it gives me:
```
TypeError: Cannot read property '_collection' of undefined
```
I declared it after the collection.
```
Companies = new orion.collection('companies', {
  singularName: 'company',
  pluralName: 'companies',
  link: {
    title: 'Company'
  },
  tabular: {
    columns: [
      {data: "name", title: "Company Name"},
      orion.attributeColumn('hasOne','productId','Product Type')
    ]
  }
});
orion.links._collection.update({ identifier: 'collections-Companies' }, { $set: { index: 1 } });

```
Thanks

**Comment by nicolaslopezj** [comment]
The identifier is with the name of the collection, not the name of the variable.
The name is ```companies``` not ```Companies```

**Comment by Ajaxsoap** [comment]
I tried it but with same error:

`TypeError: Cannot read property '_collection' of undefined
`

Should I put it on both or client only?

**Comment by Ajaxsoap** [comment]
Ok, I already figured it out. I put the code inside `Meteor.startup` function on the client.

Thanks for the help! :)
