### ISSUE TITLE
Unexpected behavior in with orion.config

### ISSUE THREAD

**Issue by josephdburdick** [orionjs/orion#283]
Hi, I'm getting undefined when trying to use .add and .get methods with orion.config.

Inside config.js:
```
orion.config.add('KAD_APPID','123456789');
```
Later on, in kadira.js:
```
Kadira.connect(orion.config.get('KAD_APPID'), orion.config.get('KAD_APISECRET'));
```
But both return undefined. Even when I use `meteor debug` to debug this from inspecting the server code I get the same `undefined` result.

**Comment by PEM--** [comment]
You should add the `type` in the `options` as it doesn't have any default.

Something like that should be good:
```js
orion.config.add('KAD_APPID', '123456789', {type: String});
```

**Comment by josephdburdick** [comment]
Thanks @PEM--
