### ISSUE TITLE
Repeating warning message about subscribing to dictionary.

### ISSUE THREAD

**Issue by josephdburdick** [orionjs/orion#284]
Running the app results in repeating messages from the server warning not to subscribe to the dictionary. It would be helpful to link to a resource from the console so I can read more about what the warning is eluding to so I can fix.

```
meteor             
[[[[[ /Applications/MAMP/htdocs/Code/Github/josephdburdick/js/meteor/clones/dahlia-orion ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
I20150821-01:24:29.676(-4)? Kadira: completed instrumenting the app
I20150821-01:24:30.245(-4)? Kadira: successfully authenticated
I20150821-01:25:12.618(-4)? Do not subscribe to the dictionary, the client is subscribed automatically. This publication will be removed and will cause errors on your app.
I20150821-01:25:13.473(-4)? Do not subscribe to the dictionary, the client is subscribed automatically. This publication will be removed and will cause errors on your app.
I20150821-01:25:15.343(-4)? Do not subscribe to the dictionary, the client is subscribed automatically. This publication will be removed and will cause errors on your app.
=> Meteor server restarted                    
I20150821-01:30:14.209(-4)? Kadira: completed instrumenting the app
I20150821-01:30:14.255(-4)? Do not subscribe to the dictionary, the client is subscribed automatically. This publication will be removed and will cause errors on your app.
I20150821-01:30:14.828(-4)? Kadira: successfully authenticated
=> Meteor server restarted                    
I20150821-01:30:23.278(-4)? Kadira: completed instrumenting the app
I20150821-01:30:23.560(-4)? Kadira: successfully authenticated
I20150821-01:30:23.603(-4)? Do not subscribe to the dictionary, the client is subscribed automatically. This publication will be removed and will cause errors on your app.
```

**Comment by PEM--** [comment]
Why do you need to subscribe to the dictionary? It's already done by default: https://github.com/orionjs/orion/blob/master/packages/dictionary/dictionary_client.js#L1

**Comment by josephdburdick** [comment]
@PEM-- Well see that's the thing, I have no idea– I haven't manually subscribed– it was doing this out of the box. There's no line number telling me where this was done, I've found a subscription in the router to the dictionary that I've comment out but I still have the same issue.

**Comment by josephdburdick** [comment]
Ok @PEM--  I think my issue is that I'm using https://github.com/iamkevingreen/Orion-Starter and I just need to burn all of this to the ground and begin with just this repo from scratch. I was hoping to bypass steps but it's proving to be more hassle than it's worth.

**Comment by PEM--** [comment]
Indeed, this project seems to have pause since some time. Orion has advanced quite a lot since then.

There's a tutorial available here http://orionjs.org/tutorials. It should put you on track.

**Comment by josephdburdick** [comment]
Thanks so much @PEM-- ! Learning how to build sites with Orion on top of Meteor is something that interests me a lot. Hopefully it'll allow me to keep learning Node without having to take tangents to Wordpress for clients that want a simple website to modify.
