### ISSUE TITLE
URGENT: Orion example listed in official docs has porn

### ISSUE THREAD

**Issue by hyrmedia** [orionjs/orion#298]
I'm not sure who's actually responsible for the project, but the example site listed on the Getting Started page of the official Orion docs has pornographic images. I'm trying to learn about the framework at work, and there was certainly no NSFW mention anywhere -- it was highly offensive and embarrassing to suddenly run into that.

**Comment by nicolaslopezj** [comment]
Sorry for that, we don't have any filter in the example. The posts were removed

**Comment by serkandurusoy** [comment]
@nicolaslopezj you should reopen this. I was demoing the example to my *sister* today when we were terrified by large close up pics of you-guess-what!

Needless to say she was not interested in hearing any more about orion and it kind of took me a couple of minutes to reassure her that this is a serious project and that I'm not a porn addict.

I think you should employ a mechanism that resets the database every hour or so. Perhaps you could also add a *NSFW* label somewhere :disappointed:

**Comment by nicolaslopezj** [comment]
Hi @serkandurusoy,

I tried a lot of mechanism to remove that images but that guy passed them.

I have work a lot for that, I tried a lot of things like implementing the flag-a-post, ban IPs, email verification and more.

Now the example shows the posts with more likes in the home, so we won't see those images anymore.

**Comment by serkandurusoy** [comment]
I'm sorry that such jerks exist but that does not diminish the value of what you are trying to accomplish.

Perhaps a better solution would be to reset the database with a fresh seed everyday.

**Comment by nicolaslopezj** [comment]
He would every day create more posts.
I think with the last change (order by likes) we will no see that again.
