### ISSUE TITLE
In a fresh meteor proyect and orion:core install the front is visible in the admin route

### ISSUE THREAD

**Issue by elidiazgt** [orionjs/orion#300]
already installed boostrapt theme

![screenshot from 2015-09-14 17 54 23](https://cloud.githubusercontent.com/assets/11800064/9864807/0bc6767e-5b0b-11e5-9d6f-a4f2324397c2.png)

**Comment by elidiazgt** [comment]
Mi packages
![screenshot from 2015-09-14 18 05 16](https://cloud.githubusercontent.com/assets/11800064/9864827/3f01d470-5b0b-11e5-9deb-be09ba78bed6.png)

**Comment by nicolaslopezj** [comment]
If you don't put the html inside ```<template>``` it will be available everywhere
