### ISSUE TITLE
Permission denied on dictionary 

### ISSUE THREAD

**Issue by iamkevingreen** [orionjs/orion#301]
I updated a very very old version of orion and spent like a day getting most of it all working again. Deleted my user and created a new admin user and can update my collections but I can't see any of the existing dictionary entries (the values from the existing entries) or save new ones:

```
details: undefined
error: 403
errorType: "Meteor.Error"
message: "Access denied [403]"
reason: "Access denied"
```

dictionary: 

```
orion.dictionary.addDefinition('siteName', 'site', {
  type: String,
  label: "Site Name",
  optional: true,
});
```

I assumed creating a fresh admin would give me access to the dictionary entries? But maybe not the case?

**Comment by nicolaslopezj** [comment]
The user must be allow to perfect the ```dictionary.update``` action. Admins are allowed by default.

Check if the user has the admin role, if not add it.
https://github.com/nicolaslopezj/roles/

**Comment by iamkevingreen** [comment]
The user does have the admin role, Users without the admin role can't even see the fields for the dictionary or custom post types. Delete the user and deleting the existing roles allows me to create a new user with admin permissions (an admin role is created in the database) but I still get permission denied when I try to update a dictionary entry.

**Comment by nicolaslopezj** [comment]
This is not the expected behavior, can I see your code?

**Comment by iamkevingreen** [comment]
I added you as a collaborator to it. It's the what-happened branch. I updated from a way earlier build of orion, everything is fine with the exception of how the admin functions. When I create a fresh user, it says they're an admin, but then I can't edit or modify anything (including my own profile). At some point on my local it worked for like 10 minutes but then I once again couldn't update things. 

(there is an existing database that isn't structured entirely right like the definitions now living in objects per the tab definition but I manually updated the database to understand the new structure)

**Comment by nicolaslopezj** [comment]
To what repo?

**Comment by iamkevingreen** [comment]
private repo, you should be emailed, sent you a private message on gitter to not clog this up anymore.

**Comment by nicolaslopezj** [comment]
The admin role is defined by default.

If you want to change the behavior of that role you can access it like this.

```js
var role = Roles.adminRole;
role.allow('xxx', true);
```

**Comment by iamkevingreen** [comment]
:tada: I think that did the trick a little strange that we had to force it but works for me.

**Comment by assutech** [comment]
Hello there! 
I still have this problem. When I try to insert a new item into the dictionary I get: 
Cannot read property '_firstLevelSchemaKeys' of null
at Object.orion.dictionary.deny.insert (dictionary.js:21:41)

Thanks in advance.
