### ISSUE TITLE
Update package constraints for less in orionjs

### ISSUE THREAD

**Issue by rwatts3** [orionjs/orion#305]
Hi Nick, 

With the release of `Meteor `1.2` we need to update the package constraints on less in the following packages. 

- orionjs:materialize 
- orionjs:summernote
- orionjs:froala
- orionjs: file-attribute 
- orionjs:relationships

less is now at version `2.5.0_1` and the package constraint is at version `1.0.11` , 
i'd be happy to submit a pr if you'd like. Let me know.

**Comment by nicolaslopezj** [comment]
Please do!
