### ISSUE TITLE
Question : How to change default message of Send Verification Email

### ISSUE THREAD

**Issue by rwatts3** [orionjs/orion#311]
Hi Nicolas,

Is there a recommended way to change the default email message to a custom one. 
Maybe an option in `Options` or in the Admin panel to set a subject, body or something along those lines. 

I know for the body we'll probably have to extend and add what ever text we'd like since it dynamically generates the invitation url. But i'm just curious if theres a easy way to add a custom message tailored to the end client's request.

**Comment by nicolaslopezj** [comment]
You must change it the same way you do with normal meteor apps
