### ISSUE TITLE
How do I resolve collection relationship order? Collection undefined

### ISSUE THREAD

**Issue by Ajaxsoap** [orionjs/orion#326]
Hi @nicolaslopezj ,

Ho do I resolve the issue of relationship in terms of order?

I have 3 collection and this 3 collection has a relationship with other.

collection Product - no field relation with Company and Insurer
collection Companies - has a Product and  Insurer
collection Insurer - has a Product and Company

Before, this collection has a separate js file each, the usual meteor collection setup but the problem is i get undefined collection. So I combine this 3 collections into one single js file and reorder the collections, i always get undefined collection whenever I re arrange it.

For example, the above setup, product collection is on top of companies and insurer, i get insurer undefined  on my companies collection because insurer is below company collection. 

How do I fix the issue?

**Comment by rwatts3** [comment]
Try extending the initial schema in a file loaded after all the other schemas are defined.

- 01- Product
- 02 - Companies
- 03 - Insurer
-04 - Schemas , where you either `$.extend` or `$_.extend` *underscore* the initial schemas introducing your relationships.

 At this point all schemas should be loaded and available for the relationships.

**Comment by Ajaxsoap** [comment]
Thanks @rwatts3 !

How do I extend the schemas? I haven't tried that yet, please enlighten me. It should be on the lower level of order like above? Could you share me a common pattern on how to extend schemas?

Here's my schema for the above collections which I've posted on the [forum](http://forums.orionjs.org/t/how-do-i-resolve-collection-relationship-order-collection-undefined/168).

I guess, from  your solution, I can now separate my collection to individual js file?

**Comment by Ajaxsoap** [comment]
Hi @rwatts3 ,

You don't need to reply, I've already fixed it.

This is in your face illogical part of me. hahaha 

I've already fixed it.

Instead of 
```
collection Product - no field relation with Company and Insurer
Product schema
collection Companies - has a Product and Insurer
Companies schema
collection Insurer - has a Product and Company
Insurer schema
```
it should be
```
collection Product - no field relation with Company and Insurer
collection Companies - has a Product and Insurer
collection Insurer - has a Product and Company
```
```
Product schema
Companies schema
Insurer schema
```
in this manner all the collection are on top of the schemas.
