### ISSUE TITLE
Arrays items in dictionnary not reordered

### ISSUE THREAD

**Issue by weeger** [orionjs/orion#343]
First congratulation for these really cool packages.

I create a dict : 

orion.dictionary.addDefinition('sentences', 'home', {
  type: [String],
  label: 'Blah...'
});

Then I fill it manually when my website is initialized : 

    orion.dictionary.update(orion.dictionary.findOne()._id, {
      $set: {
        home: {
          sentences: [
            "Yow",
            "Hey",
            "Wah",
            "Ugh"
          ]
        }
      }
    });

Then I go to my admin interface, remove the first item of the list, and save. The first item is not deleted, I mean because the [0] index of the array is kept is not reordered. 

Regards

**Comment by nicolaslopezj** [comment]
First, you should do 
```js
orion.dictionary.update(orion.dictionary.findOne()._id, {
  $set: {
    'home.sentences': [
      "Yow",
      "Hey",
      "Wah",
      "Ugh"
    ]
  }
});
```
to avoid replacing all the home category.

That problem is issue with autoform, Orion uses autoform to render forms.

**Comment by weeger** [comment]
Okay,

Thanks !
