### ISSUE TITLE
Cant delete items (objects) from collections

### ISSUE THREAD

**Issue by amazingBastard** [orionjs/orion#346]
So I recently started running into this issue.

For example, I have a Posts collection and I create a post under an admin account. However, whenever I try to delete this post, nothing happens. I click on the delete button, it takes me to the confirmation but clicking confirm delete does nothing. There is no error in the console, no redirect, the post remains in the collection. 

Any ideas what could be causing this or if anyone encountered this problem? Thanks!

**Comment by nicolaslopezj** [comment]
which version are you using?

**Comment by amazingBastard** [comment]
This was a version issue, you're right. Sorry, got it working. Thanks!

**Comment by nicolaslopezj** [comment]
Great
