### ISSUE TITLE
Can I show related fields in the table?

### ISSUE THREAD

**Issue by chmac** [orionjs/orion#347]
If I link two collections with a `hasOne` relationship, is there some way I can show the target field of in the table view, instead of showing just the ID? I realise I could dig into the tabular docs and probably achieve it that way, but I'm wondering if it's built into orion already.

**Comment by nicolaslopezj** [comment]
There is no built in way in orion.

You should create a custom publication for tabular and define the value function for your column. That  field will not be searchable.

**Comment by M4v3R** [comment]
@nicolaslopezj Couldn't this issue be left opened as a feature request? I just stumbled upon the same issue, and the workaround you suggest, while plausible, isn't ideal, especially when the field is not searchable.

**Comment by nicolaslopezj** [comment]
@M4v3R this is a feature request for tabular, but I don't think this will work with searchable ability.
Mongo doesn't query multiple collections, so its impossible.

But you can add the external fields to the corresponding documents (maybe using collection hooks).
That's the best solution I think
