### ISSUE TITLE
Rename to Cocks CMS

### ISSUE THREAD

**Issue by StasevichJack** [orionjs/orion#351]
I like the Orion CMS and went today to my boss to tell about it. We are starting a new project and I considered using Orion. After I showed the boss and all my colleagues the CMS, I wanted to show the example app. I checked the app an hour or two before and it was great.

When I started to show the [blog demo](http://orion-example.meteor.com/), I scrolled the page, showed some posts. But suddenly, the cocks started to appear on the page! **IT WAS EMBARRASSING!**

I had a very tough talk with my boss, who even wanted to fire me. Luckily, he didn't fire me but he reduced my salary and he decided to never look at orion again.

**WHY CAN'T YOU DO A NORMAL DEMO SAFE FOR USERS, HOW CAN WE EVEN CONSIDER USING THE CMS WITH COCKS?**

---

Demo now

![orion](https://cloud.githubusercontent.com/assets/9402284/11061928/ab81b462-87bb-11e5-895f-5b6569bff17f.png)

**Comment by nicolaslopezj** [comment]
Hi,
I'm sorry but the demo is open for everyone and there is a person that uploads that pictures every day.
I added features like flag post, email verification and block ips, but he has pass that.

I don't want to remove to possibility for everyone to create posts.

Now the posts that are shown in the home are the ones that have more likes, so we won't view those images.

**Comment by Lindstrom1989** [comment]
BEST GITHUB ISSUE EVER!
