### ISSUE TITLE
Unable to update dictionary

### ISSUE THREAD

**Issue by lusilva** [orionjs/orion#353]
I am not able to update any dictionary values.

I created a sample dictionary entry, as per the docs.

```
orion.dictionary.addDefinition('description', 'basic', {
    type: String,
    label: 'Description'
});
``` 

The entry appears correctly on the admin dashboard, but when I edit it and hit 'Save', nothing happens and I get the following error in the console:

```
errorClass {error: 500, reason: "Internal server error", details: undefined, message: "Internal server error [500]", errorType: "Meteor.Error"}
```

I'm using the current version of all packages (just ran meteor update) and am on Chrome.

**Comment by lusilva** [comment]
Works now, didn't realize had to run dictionary code on both server and client.

**Comment by nicolaslopezj** [comment]
Great
