### ISSUE TITLE
Orion Relationship hasOne to choose collection dynamically?

### ISSUE THREAD

**Issue by ashishapy** [orionjs/orion#354]
I want to have two fields:
1. field to choose the entity / collection to link
2. field to link _id of the entity / collection chosen above.

////////////
```
field1: {
  type: String,
  allowedValues: [
    "CollectionName1",
    "CollectionName2",
    "CollectionName3"
  ]
},

/////////
field2: orion.attribute('hasOne', {
  type: String
  }, {
    collection: [dynamicCollectionName], // coming from field 1
    titleField: 'field1',
    publicationName: 'any thing',
  })
```
This is just idea but not sure how to achieve it.

**Comment by nicolaslopezj** [comment]
That is not possible.
I would recommend to create a field for each collection you have.

Or instead of having different collections you can merge all documents into one collection and update the filter dinamically

**Comment by ashishapy** [comment]
Thanks @nicolaslopezj . Yes, I choose to create a field for each collection.
