### ISSUE TITLE
How do i override the default /admin/my-account route?

### ISSUE THREAD

**Issue by Ajaxsoap** [orionjs/orion#369]
Hi @nicolaslopezj ,

I have a dashboard route which is ```/``` ,  locally I didn't encounter the **flickering** issue but when I deployed on DO, whenever i refresh the page or loosing the connection, it will point to /admin/my-account and the domain on the address bar flickers and hangs. Here's the address of my [deployed](http://128.199.212.85/) app.

Thanks

**Comment by rwatts3** [comment]
@Ajaxsoap Orion Dashboard is not apart of the Orion Core. If you would like to submit the issue in that repo i'd be happy to take a look. 

https://github.com/rwatts3/orionjs-dashboard/issues

**Comment by Ajaxsoap** [comment]
Thanks @rwatts3, sorry but i am preferring to my own dashboard not the dashboard package that you wrote. I manually created a route for it. I think the issue is something to do with my app structure.

**Comment by rwatts3** [comment]
Oh OK.  I should have clarified that.

**Comment by rwatts3** [comment]
On that note the admin home route is an Option. . take a look at the core packages.  You should see the options for the admin home route.  Just overwrite that option by setting it to your desired route.

**Comment by rwatts3** [comment]
That's also what I did in my dashboard package.  You ca check there too if you can't find it in the core.

**Comment by Ajaxsoap** [comment]
Thanks @rwatts3 , I will take a look on it. 

Assuming that I found the right code, how do I modified it, if it's in the core package? My app is structure is not structured as a package.

**Comment by rwatts3** [comment]
You don't.  Options were written to be overwritten with Options.set
So if you call options.set it will be passed to every item that uses that
option as your new value.

**Comment by Ajaxsoap** [comment]
Oh, I see but it didn't mention on the docs [customization](http://docs.orionjs.org/v1.7/customization) section.
