### ISSUE TITLE
Enhancement request: make an option to declare a normal Meteor collection

### ISSUE THREAD

**Issue by Ajaxsoap** [orionjs/orion#395]
Hi @nicolaslopezj,

From the topic itself, I would like to have an option to declare a normal meteor collection or set an option to create a collection that is not intended to display on the sidebar as links like **client only collection**, **collection that the view is integrated to the view of another collection**, **collection that doesn't need tabular**.

I have an open [thread](http://forums.orionjs.org/t/creating-collection-for-aggregated-data-hidden-in-sidebar/218) on the forum for further details.

Thanks and more power!

**Comment by Ajaxsoap** [comment]
Hi @nicolaslopezj ,

I have an idea of a PR but I don't know how to do it. 

My idea is making the title optional, **if** no title, hide it in on side bar **else** appear on the sidebar.

**Comment by nicolaslopezj** [comment]
orion.links behave like a local collection. 
If a link doesnt have a index attribute, it wont show, so you can update the local document

**Comment by Ajaxsoap** [comment]
Thanks @nicolaslopezj !

How do I remove a collection from the sidebar?

```
orion.links.add {
    index: 
    identifer: "123"
    title: "Projects"
  }
``` 
Where should I put this code? inside ```onCreated``` ?

**Comment by Ajaxsoap** [comment]
I already figure it out.

Thanks @nicolaslopezj  for the hard work.
