### ISSUE TITLE
Leverage defining user roles.

### ISSUE THREAD

**Issue by rwatts3** [orionjs/orion#41]
Would it be possible to leverage user roles, for instance if you want to assign a role of client , or blogger and give any user within that role default permissions. 

`alanning:roles` is a great package to use as leverage. 

So similar to how you did pages extension you could do roles extension, and have an entity that you can define presets based on a role.

**Comment by nicolaslopezj** [comment]
Something like permission groups?

**Comment by rwatts3** [comment]
Correct. for instance if I want to create an invitation, on the left I see admin. What if I wanted to select client, and only give them permission to content, collection instead of navigation.

**Comment by rwatts3** [comment]
I would be on board with creating an extension that would leverage this.

**Comment by nicolaslopezj** [comment]
@rwatts3 I don't think this is posible with an extension. Some changes in the core are required.

**Comment by rwatts3** [comment]
@nicolaslopezj you make a very good point. I have an alternative solution that may work. So creating an entity called roles , then a property within the entity which would be a multi select lookup of current users. You can select multiple users for each role. This doesn't really work in terms of permissions for admin, but throughout the site, the roles entity can be used to determine which users to display content or not. 

If the user is not selected within that drop down, then the content will not display. 
Again purely front end. Let me know your thoughts.

**Comment by nicolaslopezj** [comment]
Thats a good idea. 
But anyways, I think [here](https://github.com/orionjs/core/blob/master/users/common.js#L56) we should give the possibility to the developer (or the extension developer) to say if the user has permission and skip the normal checking of permissions

**Comment by rwatts3** [comment]
Good point, what are you thoughts on that ?

**Comment by nicolaslopezj** [comment]
Maybe this can solve this issue
https://github.com/orionjs/core/tree/master/users#custom-permissions-for-entities
