### ISSUE TITLE
Relationships : Match error: Expected particular constructor in field collection

### ISSUE THREAD

**Issue by jannikkeye** [orionjs/orion#419]
Hi,

I have my 3 collections. Each is stored in a different file that exports the collection. This error only occurs when trying to import another collection and assign it to the collection field of a relationship. When all my collection definitions are in one file it works fine.

The export looks like this: 

```javascript
export const Alumni = new orion.collection('alumni', {
    singularName: 'alumnus',
    pluralName: 'alumni',
    title: 'alumni',
    link: {
        title: 'Alumni'
    },
    tabular: {
        columns: [{
                data: "_id",
                title: "ID"
            }, {
                data: "firstname",
                title: "Vorname"
            }, {
                data: "lastname",
                title: "Nachname"
            }, {
                data: "email.address",
                title: "Email"
            },
            orion.attributeColumn('image', 'avatar', 'Avatar'),
            orion.attributeColumn('images', 'projects', 'Projects'),
        ]
    }
});
```

I import the Alumni variable as follows:

```javascript
import { Alumni } from '../alumni/alumni.js';
```

and then use it like this.

```javascript
alumni: orion.attribute('hasMany', {
        label: 'In diesem Magazin'
    }, {
        collection: Alumni,
        titleField: ['lastname'],
        publicationName: 'In diesem Magazin',
        additionalFields: ['lastname', 'fullname']
    })
```

Somehow I get an error that looks as follows:

<img width="1004" alt="bildschirmfoto 2016-06-06 um 17 39 17" src="https://cloud.githubusercontent.com/assets/10485074/15827938/b09f8266-2c0d-11e6-96b4-8aaf9ee426fd.png">

I really want to keep the files separated for better orientation.

thank you in advance,
Jannik

**Comment by jpabluz** [comment]
Bump, I get this same error on updating to Meteor 1.3.3.1, not on Meteor 1.3.3... Any ideas?

I fixed it by downgrading but I don't want to get stuck with this version.

**Comment by rwatts3** [comment]
Certainly interesting. I'll test and see if I can reproduce.

**Comment by rwatts3** [comment]
Are you importing the same collection into itself ?

**Comment by jannikkeye** [comment]
Sorry for the late answer.

I don't think I did. But I just tried to separate the files again and now everything works fine. Thank you for looking into this though. Would have forgotten about this otherwise!

Thanks again!

**Comment by JulianKingman** [comment]
I'm having the same issue, here's my collection definition:

````javascript
const Leagues = new scorpius.collection('leagues', {
  singularName: 'League', // The name of one of these items
  pluralName: 'Leagues', // The name of more than one of these items
  title: 'Leagues', // The title in the index of the collection
  link: {
    title: 'Leagues', //sidebar
  },
  tabular: {
    pub: 'leagues/admin',
    columns: [
      {data: 'Games', title: 'Game', render(gameId) {
        const game = Game.findOne({_id: {$in: gameId}});
        return game && game.name;
      }},
      {data: 'title', title: 'Title'},
      {data: 'avatarUri', title: 'Avatar'},
      {data: 'Teams', title: 'Teams', render(teamIds) {
        const teams = Team.find({_id: {$in: teamIds}}).fetch();
        if (!teams.length) return 'No teams';
        return _.map(teams, (team) => team.title || 'Pending');
      }},
    ],
  },
});

Leagues.attachSchema(new SimpleSchema({
  _isNew: {type: Boolean, optional: true},
  title: {type: String, label: 'Title', optional: true},
  _id: {type: String, label: 'League ID'},
  avatarUri: {type: String, label: 'Avatar Image URL', optional: true},
  Teams: scorpius.attribute('hasMany',{
    // type: Array,
    label: 'Teams',
    optional: true,
  },{
    titleField: 'title',
    publicationName: 'teams/leaguesAdmin',
    collection: Teams,
  }),
// ...more
});
````

@rwatts3 @jannikkeye  any idea what the source of this issue is?

**Comment by JulianKingman** [comment]
In the specified file, it's matching collection to `Mongo.collection`, is that allowed? I can't find any documentation on validating collections using `Match`

**Comment by jannikkeye** [comment]
@JulianKingman If I remember correctly the problem was that I was importing the collection where I used my collection into the collection that I was importing. Thats what caused the error for me.

@rwatts3 was actually right.
> Are you importing the same collection into itself ?

**Comment by rwatts3** [comment]
I'd also like to note this issue may be fixed already in Scorpius.
Have you gone through the migration process ? I believe at this point in
time Orion.js may still be deprecated.
Checkout https://github.com/scorpiusjs/scorpius

**Comment by JulianKingman** [comment]
Yes, I'm on scorpius, I just didn't want to open a new thread. I think my issue was importing from the wrong file.
