### ISSUE TITLE
Question : How do you define in the defaultPermissions restricting file behavior to user specific.

### ISSUE THREAD

**Issue by rwatts3** [orionjs/orion#54]
How do you restrict file behavior to the specific user. 

For instance entity.notes.personal allows you to only allow personal notes assigned to that user. 
I would like to do the same thing for files. If the user didn't create the file I would like them not to be able to delete it.

**Comment by nicolaslopezj** [comment]
This is not currently implemented. You can make a pull request on filesystem with the changes.
