### ISSUE TITLE
CKeditor and TinyMCE

### ISSUE THREAD

**Issue by rwatts3** [orionjs/orion#59]
I am not sure why anyone would want to use any of these editors but I figure that since we have the other two options we might as well at these as well. I am going to work on creating extensions for both of these editors for any other users that may potentially want to use them. I personally do not like either one of them but I believe that someone out there would probably want to use them so it would be a good idea.

**Comment by nicolaslopezj** [comment]
I think a code editor would be great. Maybe ace editor http://ace.c9.io/

**Comment by rwatts3** [comment]
Ace does look promising.  I will look into adding that to the stack as well.  Im also curious as to how we could create variables that will be parsed when the content loads for instance let's say the user is using froala. How could we make it so that {dict 'variableName'} would be escaped and rendered upon page view.  In case they want to dynamically add content within their actual text

**Comment by nicolaslopezj** [comment]
You can do that with triple braces

```html
{{{ dict 'froalaContent' }}}
```

**Comment by rwatts3** [comment]
This does not work can you give me an example of how you accomplished this task.  I assigned the variable inside the editor content and it renders the code to the page instead of the code parsed.

**Comment by nicolaslopezj** [comment]
I'm sorry, I don't understand what you are trying to do
