### ISSUE TITLE
Custom entity templates

### ISSUE THREAD

**Issue by nicolaslopezj** [orionjs/orion#60]
Set custom templates to entities. For example, in a entity that represent events, show a calendar instead of the table.

Suggest ideas if you have

**Comment by iamkevingreen** [comment]
Not really sure where you are going exactly with this one, but in terms of calendars http://fullcalendar.io/ is my goto. looks like it's been ported over a bit here: https://atmospherejs.com/rzymek/fullcalendar

But the callbacks for fullcalendar are totally documented it's a really solid solution for calendars

**Comment by timfam** [comment]
@iamkevingreen You talking about presentation or event entry form? entry is orionjs but for presentation it is out of scope of this project. So please clarify question

**Comment by nicolaslopezj** [comment]
Instead of showing the table, you can choose. An example was the calendar, same functionality that the actual table has but a different way to display it. It can be other things, like showing entity items like in the files tab.

**Comment by timfam** [comment]
@nicolaslopezj you are right about using the fullcalendar this needs a robust solution. I also think he may be asking how to display it to visitors  (non-login guest). This is why I wanted to know the usecase

**Comment by nicolaslopezj** [comment]
@timfam, you are right. This is only for the admin, anything is its out of the scope
