### ISSUE TITLE
Add sub level admin nav items 

### ISSUE THREAD

**Issue by rwatts3** [orionjs/orion#62]
Not sure if someone has mentioned it but we should add the ability to add sub level navigation items.  So keep all Homepage related entities under one navigation item.

**Comment by timfam** [comment]
@rwatts3 you mean like a dropdown menu?

**Comment by rwatts3** [comment]
Correct.  But with the items we add to the entity.  Or admin area . So let's say we want to add an entity but we want the entity to be a child of another entity.  Purely for visual organization.  We could put entity A and then under an orion attribute called parent we could put entity B.  Therefore in the admin panel entity B will be under a drop down of Entity A taking up less space in the admin area and properly grouping it.

**Comment by timfam** [comment]
Makes sense I think it is the ``` orion.admin.addSidebarTab ``` that needs to be extended to add this functionality. Like adding a parent - child property. I will look into it when I have some free time in the future. Good idea.

**Comment by rwatts3** [comment]
Thanks.  I will look into it as well maybe we can collaborate on direction and PRs

**Comment by rwatts3** [comment]
I also think some changes may have to be made in the fire do to the way the sidebar is structured.  Nothing is looping over the Ul. And there is no li.  So we could restructure to loop over Ul and if an li is present drop it directly underneath the names parent.

**Comment by timfam** [comment]
@nicolaslopezj Your thoughts on looping?

**Comment by nicolaslopezj** [comment]
I totally agree on what @rwatts3 said about related entities, it's a good way to show its a child.
Choosing the parent in the entity definition could be a good idea.

**Comment by timfam** [comment]
So we add a parent field in the definition and rendered it in a child ```li```?

**Comment by nicolaslopezj** [comment]
Add the option here https://github.com/orionjs/core/tree/master/entities#creating-entities in the options fields, beside to icon, etc.
I don't care about with method we use to show it in the sidebar, but it should look well and work fine

**Comment by rwatts3** [comment]
Alright.  I'll begin work on the pr . I'm going to keep this in core since its directly working with the base.html file  And entities option.

**Comment by nicolaslopezj** [comment]
Yeah, the code changes must be in the core and bootstrap

**Comment by rwatts3** [comment]
In Progress
After looking at the code I realized that assigning parents and children is more complicated than proven worthy. Instead I'm adding options called `sideBarGroup` and `sideBarGroupIcon` . 

The group name will put the entities under a subnav related to the Group Name.

**Comment by nicolaslopezj** [comment]
This is the same as #52
