### ISSUE TITLE
Q: Is Orion playing nicely with others?

### ISSUE THREAD

**Issue by mraak** [orionjs/orion#63]
For example Reaction Commerce? Say I create a blog with Orion and in posts I'd like to use products ("entities") for sale from Reaction Commerce.

https://github.com/reactioncommerce/reaction

**Comment by nicolaslopezj** [comment]
Orion isn't intrusive. I think you can integrate with that reactioncommerce. I haven't integrate it with that yet.
If you are doing it please share your results

**Comment by timfam** [comment]
@mraak I am interested too, let me know how I can help

**Comment by mraak** [comment]
I'm not having this in the immediate pipeline, but I will soon do some live projects on Orion so something like this might come up soon. Once I have something I'll post here.

**Comment by timfam** [comment]
Ok keep us posted. Orion rocks!
