### ISSUE TITLE
Message when orion attribute its not installed

### ISSUE THREAD

**Issue by mraak** [orionjs/orion#66]
Not sure what I'm doing wrong. I installed the dependencies as described in Getting started, then created a new project, and copy pasted the entities folder there from this project: https://github.com/orionjs/example-blog

This is what I get. Do I have to install something more or what?

.meteor/packages/meteor-tool/.1.1.2.1kfqnpj++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
TypeError: Cannot read property 'getSchema' of undefined
    at Object.orion.attribute (packages/orionjs:core/attributes/common.js:33:1)
    at app/entities/posts.js:22:15
    at app/entities/posts.js:57:3

**Comment by nicolaslopezj** [comment]
You have to install the attribute that the example uses https://github.com/orionjs/example-blog/blob/master/.meteor/packages.

We should add an error that says something like "attribute not found"

**Comment by mraak** [comment]
Works now. That would be helpful yes, also, since you're architecture relies on many small packages, you could create a table of all of them and where and why they're used. 

I haven't seen anything in your Getting Started or here: http://orion.meteor.com/docs/entities, that would suggest which ones I need to install.

Thanks!

**Comment by nicolaslopezj** [comment]
Not everyone needs the same packages, but I agree about showing which package uses orion-example.
Can you do a pull request to the readme?

**Comment by nicolaslopezj** [comment]
We still need some help here with the message on the code

**Comment by mraak** [comment]
Did it on the example project. I think you should still add this to Getting Started, just list all the packages and create links to them. 

As for help with error message, point me to where this is and if I'll have time I can look into it.

**Comment by nicolaslopezj** [comment]
Here it is https://github.com/orionjs/core/blob/master/attributes/common.js#L33. 
Thanks
