### ISSUE TITLE
Not able to actually add/edit users

### ISSUE THREAD

**Issue by mraak** [orionjs/orion#68]
Can only create invitations. Is this on the roadmap and is there a workaround?

**Comment by rwatts3** [comment]
There is an option for allowing users to register via the front end , with a "register" link. This allows the user to register on their own. 

```js
orion.users.configure({
    forbidClientAccountCreation: false,
    defaultPermissions: ['entity.posts.personal']
})
```

**Comment by mraak** [comment]
I was thinking of adding them from admin. Once you click "Create" on the users panel, you can only create an invitation. I'm thinking if it's possible to actually get fields where you can enter users email and create a user. 

btw, I added your code, but how do I add register link to the page? Is there another package for that and what is the syntax?

**Comment by rwatts3** [comment]
ok so 
```js
forbidClientAccountCreation: false,
````

actually enables the `register` link. so if you go to `/login/` and you are not a logged in user , you will see the register button at the bottom of the page. Inside of the defaultPermissions , is where you determine what options the users get by default. If you set this to false this means users can not register unless you directly send them an invitation. So let's say you have an entity called events. And you do not want users that you haven't approved to see that entity . you would restrict the permissions in defaultPermissions to only be `entity.events.admin` which means only admin users or users you specify can access or even see that entity. 

![image](https://cloud.githubusercontent.com/assets/5336137/6994429/481d7e0a-dace-11e4-9232-a7d48ca3e7b6.png)

**Comment by mraak** [comment]
Thanks for this it's very useful but it still doesn't answer original question.

**Comment by nicolaslopezj** [comment]
@mraak, you can't right now. If you want you can make a pull request with the changes, I can guide you.

**Comment by mraak** [comment]
Basically my use case is the following:

- have the CRUD panels for users that work same as for other entities (with also having "active" or "published" flag)
- have each user have a profile entity (various fields)
- a user can create "organization" entity and invite new users to that organization. They all have permissions to use all entities belonging to organizations, like create, edit posts for that organization. 

It would be great if some of this I can contribute to Orion, and of course if you could provide some guidance.

**Comment by nicolaslopezj** [comment]
That's great. Can this be a package?

**Comment by mraak** [comment]
I'd say have the CRUD for users built right into core. Then have to to more packages:

- orion-profiles, one that deals with users having more info about them as profiles. Such as Django profiles package.

- orion-organizations, or orion-groups, where org creation and internal permission assignments (by org admins) would work.

**Comment by nicolaslopezj** [comment]
Great @mraak. How the crud is compatible with the current invitation system and editing permissions?

How orion profiles would work?

How orion organizations compatibilice  with current permissions system?

**Comment by mraak** [comment]
These are all the things I'd have to research, since I only started to look into Orion. But CRUD for users could be just a table, as for other entities, and then be able to edit and delete users, just as you would posts for example.

I'd need to dig into the Orion code a bit to see how to do the other two things, if you could provide some guidance for new committers that would be great.

**Comment by timfam** [comment]
Sorry guys I am late. Orionjs must first incorporate roles https://atmospherejs.com/alanning/roles in any robust platform permission is role based. then users with certain roles can create organisation etc. The organization package can extend this roles furthers to have internal permission too. The permission matrix is one of the most complex part of any serious platform

**Comment by mraak** [comment]
@timfam Right, I thought this is maybe already used with the current permission system.

**Comment by nicolaslopezj** [comment]
@timfam orion has a different permission system, more adapted to this framework. The documentation is online.

@mraak Lets start with one thing, crud users. You can tell me in which parts you have trouble.

I'm planning to do a big code clean up, and some api changes, so lets wait a little before making changes to the core of the core (permissions)

**Comment by timfam** [comment]
@nicolaslopezj Yes I know about the existing permission system, but it will soon get out of hand, it's easier to assign rights to 4 roles than to 500 users. so if @mraak is looking towards user crud then it is about time for taking a peek into roles integration. There has to be a way to make it work

**Comment by nicolaslopezj** [comment]
What do you mean by assign rights to 4 roles than to 500 users?
Ask me use cases and I will tell you how you can do it with this system

**Comment by mraak** [comment]
I wanted to create something similar to Orion - CRUD Panels package, but realized you guys are much more far ahead so I'd rather use this. One thing I had to do is have separate systems for users CRUD and for other collections (schemas). We used roles from the beginning.

**Comment by nicolaslopezj** [comment]
Orion permissions system its not too different to roles, don't be afraid

**Comment by kevohagan** [comment]
i agree with @timfam, using alanning:roles would be a better solution for
the long term.

For the moment when creating a user you can check permissions for different
actions : entities.post, entities.delete , dictionary.images etc etc

It would be much easier on the long term to definte permission using user
roles : admin, editor, normal user etc

and then inside the admin role defining orion permissions.

Makes sense?

**Comment by timfam** [comment]
I mean it easier for admin to assign permissions to roles i.e [guest, authenticated, editor, manager, admin] then assign arbitrary numbers of users to each role. very simple and how it's done in all enterprise apps or CMS. If I don't want a user to get certian permissions and just remove them from the "editor" role

**Comment by nicolaslopezj** [comment]
Ok, this makes sense to make. I will change it to roles on version 1.0 along with the code clean up

**Comment by timfam** [comment]
We should try and integrate with the exisiting roles package if possible, this is make it easier for people migrating into Orion that already using roles in their applications

**Comment by nicolaslopezj** [comment]
Yes, this will take a while

**Comment by timfam** [comment]
We will all do it together. I think roles is damn important to every one here

**Comment by rwatts3** [comment]
I agree take a look at alanning:roles for example.

**Comment by mraak** [comment]
alanning:roles is also supporting groups, which could be used for managing organization specific privileges. 

I agree with @timfam, this is very important for all of us. 


Short example from https://github.com/alanning/meteor-roles

Roles.addUsersToRoles(bobsUserId, ['manage-team','schedule-game'])
Roles.addUsersToRoles(joesUserId, ['manage-team','schedule-game'], 'manchester-united.com')
Roles.addUsersToRoles(joesUserId, ['player','goalie'], 'real-madrid.com')

Obviously here the last parameter could simply be replaced with the organization ID.

**Comment by timfam** [comment]
Using roles for organizations not very good idea. What if you want to
expose a page for the organization?  Organizations should be entity like
with the ability to support departments and have attributes.  Organizations
admin should be separate from roles admin.

**Comment by mraak** [comment]
I was even thinking of rolling out my own specific organization functionality without creating a package. All I need is group/role based privilege management more or less. 

Having orgs with departments, subdepartments, clubs, and whatnot is way to complex for what I had in mind. I don't need a full ERP, just owner, admins and publishers, preferably with auto-built UI for that, hence Orion.

**Comment by timfam** [comment]
We don't need all that feature set yet. However it has to be extensible,
you make the base with the features you need and some one else can build on
it later
