### ISSUE TITLE
Orionjs Tutorials

### ISSUE THREAD

**Issue by rwatts3** [orionjs/orion#69]
Hi @nicolaslopezj 
I have been bouncing around through the different packages and extensions and I am noticing that although the readme.md docs and examples are reat for prestine developers, there are a lot of people in the community that are very new to meteor and are extremely excited about Orion however some of them may be getting lost in terms of the best practices and ways to implement the app they are trying to build. 

I am going to work on a tutorials app, that will examplain in detail , how to build basic apps such as the example blog, and why the app is structured in the way that it is. This will do a lot of the hand holding for people that may needed it, and allow them to quickly hit the ground running with a working app rather than just cloning the example-blog and starting directly in the code. Some people need the "Why" and "How" behind the logic of example-blog in order to build their app. I believe having tutorials will eliminate a lot of the questions that are basic "I don't know how to" type of questions. I would like to know your thoughts on building. I like how you have orion.meteor.com/docs. I was thinking somoething along the lines of tutorials.orion.com or orion.meteor.com/tutorials.

**Comment by rwatts3** [comment]
P.s. I am happy to take this on and start the initial building once I hear your thoughts and guidance.

**Comment by nicolaslopezj** [comment]
Great, awesome.

It would be a great idea to have a repository with tutorials (I can give you permissions) and make the orion website automatically fetch them. This way anyone can contribute too.

Good motivation! Thanks!

**Comment by mraak** [comment]
+1

I could also chip in an example here and there.

**Comment by rdewolff** [comment]
+1

**Comment by rwatts3** [comment]
Write your examples and submit a pull request to the tutorials repository.  I'm in the process of writing a boilerplate for the tutorials now.
