### ISSUE TITLE
Merge all repositories

### ISSUE THREAD

**Issue by nicolaslopezj** [orionjs/orion#70]
I was thinking in merging all the repositories into this, as [meteor does](https://github.com/meteor/meteor/tree/devel/packages). Having each package in a different folder.

Why? 
One of the reasons is because when someone wants to send a pull request they have to send it to different repositories, with this change that would be a lot easier.
Also, is faster to send updates

This change could also come with changing the name of the repository, from orionjs/core to orionjs/orion. This of course only the repository name, not the packages.

What do you think?

**Comment by iamkevingreen** [comment]
I think this is a good idea, it will also prevent duplicate/confusing tickets/issues. Especially since this is sort of an all in one thing anyway, just with the pieces removable as you need them.

**Comment by timfam** [comment]
Plus 1

**Comment by rwatts3** [comment]
I agree as well.  You can assign a label to each package and issues relating to a specific package could be assigned accordingly.  I work a lot with SCRUM.  And even moving to a scrum approach for the team would be cool.  Check out my repo to see how I have organized my issues based on SCRUM methodologies.  It makes for easier collaboration and control of the overall project.  And the labels for issues show the user details about where the issue stands . 
Each project could be assigned a color such as purple and have a prefix like this proj : core , proj : bootstrap
https://github.com/rwatts3/orionjs-maps/labels

**Comment by rwatts3** [comment]
Also for Api documentation we should really look into docmeteor I have just started using it and it is amazing.  Aldeed autoform uses it.  And it looks really clean and will actually solve a lot of the Api questions.  Go to aldeed autoform and look at Api.md and Api.internal.md.  Docmeteor auto generated the Api based on the package.js file.

**Comment by timfam** [comment]
Actually the best way to approach a project is using afeature tree at a high level  
![image](https://cloud.githubusercontent.com/assets/10576880/7030968/6660c0e2-dd36-11e4-85d3-379ee6ee9f5a.png)

IMHO nothing beats a visual representation of hierarchy of tasks, goals, objective
