### ISSUE TITLE
Entities - multiple files

### ISSUE THREAD

**Issue by rdewolff** [orionjs/orion#71]
How can I specify that I want some entity to be an array of files?

For an array of String, we do something like : 

```
myString: {
      type: [String],
      label: "myLabel"
    }
```

How can I do that for the files that are like :
```
myFiles: orion.attribute('file', {
      label: 'myFile'
    })
```

Thanks for your help!

**Comment by rdewolff** [comment]
Or should we use alternative solution to do that?

**Comment by nicolaslopezj** [comment]
Check this https://github.com/orionjs/file-attribute/issues/3
