### ISSUE TITLE
Custom entity form

### ISSUE THREAD

**Issue by timfam** [orionjs/orion#72]
Take a look at https://github.com/timfam/core/blob/master/admin/client-common/entities.js template can now be set by developer but we need to move it to db. I am thinking add to entities.options. @nicolaslopezj  I need your guidance here

**Comment by nicolaslopezj** [comment]
What do you mean by add it to db? 

I think the best way is to set as property of the entity object the template. Like orion.entities.posts.indexTemplate, orion.entities.posts.createTemplate, etc. 

And set them using options in the entity definition, next to pluralName, etc.

**Comment by timfam** [comment]
Yes this is what I have done. But it has to be stored as an array somewhere for retrieval as Entitylist are you on freenode lets discuss it for a few minutes?

**Comment by nicolaslopezj** [comment]
I'm not on freenode, we can chat in Google hungouts. My email is in my profile

**Comment by timfam** [comment]
Don't you need a gmail account to use hangout?

**Comment by nicolaslopezj** [comment]
No, I use it with that one

**Comment by timfam** [comment]
Bear with me, I am trying to figure out how to invite you. I confess I hardly use hangout, skype is my preference

**Comment by nicolaslopezj** [comment]
Let's use Skype, nicolaslopezj. 
I'm sorry I'm on my phone, can't connect to irc
