### ISSUE TITLE
Etherpad for project maintainers

### ISSUE THREAD

**Issue by timfam** [orionjs/orion#75]
Hosting a new instance of etherpad dedicated to orionjs, this should allow for quick collaboration http://45.33.83.72:9001/ @nicolaslopezj  I can make it a subdomain of your site if you prefer that.

**Comment by nicolaslopezj** [comment]
We don't have any site, maybe we should buy a domain

**Comment by timfam** [comment]
Find the name and I can buy it if you like

**Comment by nicolaslopezj** [comment]
Don't worry @timfam, but thanks!
What do you think about orionjs.org?

**Comment by nicolaslopezj** [comment]
Ready, how do we add it to etherpad?

**Comment by timfam** [comment]
Point the domain nameserver to ns1.linode.com, ns2.linode.com to ns4.linode.com and I will add it to the hosting panel.

**Comment by nicolaslopezj** [comment]
Can we do this without only changing cname records?

**Comment by timfam** [comment]
Yes I suppose so, if you want to use it as subdomain. You have to do cname from your end

**Comment by nicolaslopezj** [comment]
Where do I point it?

**Comment by timfam** [comment]
45.33.83.72
and we access it as subdomain.domain.com:9001

**Comment by nicolaslopezj** [comment]
And can you change it to port 80?

**Comment by timfam** [comment]
Only if I use nginx server as a proxy. lets use it this way for now,
when I have some spare time i will get that done
