### ISSUE TITLE
New api for entities

### ISSUE THREAD

**Issue by nicolaslopezj** [orionjs/orion#76]
I would like to make a change to the current entity declaration. 
I want to make it more similar to meteors way, so its easier for new users.

Something like this:
```js
Posts = new orion.entity('posts');
Posts.setSchema(schema);
...
```

**Comment by kevohagan** [comment]
I like the idea! I found that namespacing in orion was a bit to opinionated
at the beginning to understand it well, i guess something closer to Meteor
specifications would be easier for onboarding new devs

**Comment by timfam** [comment]
Agreed!
