### ISSUE TITLE
Local Filesystem

### ISSUE THREAD

**Issue by matteodem** [orionjs/orion#8]
Cool package. I saw a section about Filesystems, but it only showed S3 and no clear description of how to use it for local filesystems. Please add this to the docs or show me an example here.

**Comment by nicolaslopezj** [comment]
I have not create a adapter for local filesystem, but it's very easy to create an adapter.

- Create the upload function:
```js
orion.filesystem.providerUpload = function(options, success, failure) {
    /**
     * Here you will recive the file in the variable options.fileList.
     * You have to upload the file using the method you want.
     * If the file was uploaded successfully call success(fileUrl)
     * If not call failure(error)
     */
}
```

- Create the remove function:
```js
orion.filesystem.providerRemove = function(file, success, failure)  {
   /**
     * Here you will recive the file object, containing the url and 
     * the optionalData in file.meta.
     *
     * You have remove the file.
     *
     * If the file was removed successfully call success()
     *
     * If not call failure(error).
     */
}
```

You can see an example here https://github.com/orionjs/s3/blob/master/lib/main.js

**Comment by nicolaslopezj** [comment]
If you create an adapter please upload it to atmosphere so everyone can use it!

**Comment by matteodem** [comment]
I'll see if I have time the next days.

**Comment by matteodem** [comment]
Is this implemented now :wink:?

**Comment by nicolaslopezj** [comment]
No, its not. Just answered the question

**Comment by matteodem** [comment]
Then there's a missing ticket for the actual feature, right?

**Comment by nicolaslopezj** [comment]
Nope, just answered your question. You said you're going to do it

**Comment by matteodem** [comment]
"I'll see if I have time the next days, thank you for the answer." not seeing anything that states that I would do it. But it's your decision after all.

**Comment by nicolaslopezj** [comment]
Ok, lets leave this open better

**Comment by rdewolff** [comment]
Any news concerning this file upload on the local filesystem?
Any example on how to bind this with https://github.com/aldeed/meteor-cfs-autoform maybe?

**Comment by nicolaslopezj** [comment]
@rdewolff using another provider has nothing to do with autoform. Just fill the functions! It's super-easy, give it a shot. I haven't read cfs docs, but the solution might be similar to this:

```js
orion.filesystem.providerUpload = function(options, success, failure) {
     CFS.uploadFile(options.fileList, function(error, response) {
          if (error) {
               failure(error)
          } else {
               success(response.url, { localPath: response.localPath })
          }
     })
}

orion.filesystem.providerRemove = function(file, success, failure)  {
     CFS.removeFile(file.meta.localPath, function(error, response) {
          if (error) {
               failure(error);
          } else {
               success();
          }
     })
}
```

If you put that code in your app (of course that will not work because it's not the real cfs api) all file inputs will use that functions to upload files

**Comment by rdewolff** [comment]
Am trying to use FS.Collection to do this but it's not working. I got problems to handle the file upload and calling the success function.

Could your provide a more detailed example please?

**Comment by rdewolff** [comment]
cf. https://github.com/CollectionFS/Meteor-CollectionFS

**Comment by rdewolff** [comment]
Seems that the "success" function called at the end of the file upload is not accepting URL with Port number!

**Comment by rdewolff** [comment]
Here is the code am using : https://gist.github.com/rdewolff/5777563b491ac27544ec

**Comment by nicolaslopezj** [comment]
Can you make a pull request on filesystem to accept files with port? It currently uses SimpleSchema.RegEx.Url to check. 
https://github.com/orionjs/filesystem/blob/master/lib/collection/init.js

**Comment by rdewolff** [comment]
Actually it's not the port number causing problem, but a host name without ".com" or "dot something".

**Comment by rwatts3** [comment]
Any updates on this implementation. I am willing to work with someone if they would like to collaborate to come up with a solution.

**Comment by nicolaslopezj** [comment]
@rwatts3 I think @rdewolff solution might work with the new update of filesystem https://github.com/orionjs/filesystem/commit/de9ad944f7ba2fa4163b2a97e79213c7db3e1db8 (Don't check urls)

**Comment by rwatts3** [comment]
ok so I should just update filesystem and remove `orionjs:s3` and it should work ?

**Comment by nicolaslopezj** [comment]
If the only thing that was preventing @rdewolff solution to work was the checking of the urls, it should work.

**Comment by rwatts3** [comment]
Hmm , ok I will give this a shot. @rdewolff When ever you have the solution solved are you planning on creating an extension package ? such as `orionjs:filesystem-local`

**Comment by rdewolff** [comment]
Thanks @nicolaslopezj for updating the url type to String. The error concerning localhost has been already reported earlier, cf https://github.com/aldeed/meteor-simple-schema/issues/239.

Concerning the file upload on file system, I think a simple package would be great. Let's do that!

**Comment by rwatts3** [comment]
@rdewolff I will be willing to work with you to create a package if that is okay with you. Let me know what ideas you have.

**Comment by rwatts3** [comment]
@rdewolff Could you post a gist on the code you are using to get this working. I tried to view the gist posted earlier but for some reason it's not available anymore. 

Thanks

**Comment by rwatts3** [comment]
@nicolaslopezj are you planning on doing the official extension for this ? if you are i'd like to work with you and assist. I would do it myself but would like to make sure it'd done the correct way with your insight on future extension of orionjs

**Comment by nicolaslopezj** [comment]
I'm not going to make a official extension. But if anyone make one, I would help.

**Comment by rdewolff** [comment]
hey @rwatts3 - here is the gist for the file upload. Notice is just a basic implementation to support single file upload and there is no delete method implemented yet.

https://gist.github.com/rdewolff/84ed3f3be3f24f58c1db

**Comment by loongmxbt** [comment]
Will Orionjs v1.0 include the local filesystem feature? The current implementation has no delete method and every time I upload an image, the page will automatically refresh and then display the right image.

**Comment by loongmxbt** [comment]
Just now I made a package that includes delete method. But the code is not so good-looking. After all it works. Hope it's helpful for the release of official local filesystem package.

https://gist.github.com/loongmxbt/da2b361785ca6f9ad574

**Comment by nicolaslopezj** [comment]
https://github.com/lc3t35/orion-filesystem-local
