### ISSUE TITLE
Assign Data Attribute and Class to Orion Attributes

### ISSUE THREAD

**Issue by rwatts3** [orionjs/orion#83]
I am building a tooltip extension for Orion. I would like to know how and what is the best way to pass a class and a data attribute to the afFieldInput of the orion attribute.

These are the only two components I need to render the tooltip. 

The tooltip takes a class , and looks for `data-tooltip="Tooltip's content"` where the content of the data attribute is the content of the tooltip.

**Comment by timfam** [comment]
This should work ``` {{> afQuickField name='firstName' class="classname"}} ``` If you are using ```defualt quickform``` the only way would be through the schema
