### ISSUE TITLE
How to render Tabular Table on front end using an entity.

### ISSUE THREAD

**Issue by rwatts3** [orionjs/orion#84]
I would like to render the Tabular Table of an entity on the front end for users to search the table. 
I keep receiving the following error when I try this. 

```sh
You must pass Tabular.Table instance as the table attribute
```

**Comment by timfam** [comment]
I have seen this error too but never had time to investigate. I was going to work on this over the weekend

**Comment by rwatts3** [comment]
Ok sweet , i'll keep working at it too let me know what you find i'll post any solutions or updates here.

**Comment by rwatts3** [comment]
Not related to this issue, but I'm trying to assign a class to the label of my entity with autoform. When I assign the class the class get's added to the input field but not the label. Any idea how to do this ?

**Comment by timfam** [comment]
Add a label 
```
<label class="classname">{{afFieldLabelText name='inputname'}}</label>
    {{> afFieldInput name='inputname'}}
```

**Comment by rwatts3** [comment]
but i'm doing this from the schema 

```js
 test : {
    	type: String,
    	autoform: {
         "label-class": 'simptip-position-top',
      	"data-tooltip": "ToolTip Example",
      	placeholder: 'foo'
    	}
```

**Comment by rwatts3** [comment]
Crap I've been looking at this for the past 3 hours, and I finally just went to the simple schema repo and the answer was right in my face I could shoot myself right now.

**Comment by timfam** [comment]
:) yes happens to everyone

**Comment by rwatts3** [comment]
Ok after what seemed like years I finally got this working. 

```js
 test : {
    	type: String,
    	autoform: {
	      	"label-class": 'simptip-position-right simptip-smooth simptip-info simptip-multiline',
	      	"label-data-tooltip": "This is a test to render the tooltip form.",
    	}
    },
```
![image](https://cloud.githubusercontent.com/assets/5336137/7039165/5d835e62-dd72-11e4-8330-d62d607d28ca.png)

**Comment by timfam** [comment]
Super awesome!

**Comment by rwatts3** [comment]
I spoke to @nicolaslopezj  a while back about adding an option to render categories for a pages and he gave me an example in one of my prs from the old repository. Well now that they are all merged I can't go back to see that code sample. 

Do you know how this could be done. 

I remember the end result was something similar to this. 

```html
{{# each pages template="pagesSimple" category="fooBar"}}
				<a href="{{ path }}">
					{{ title }}
				</a>
			{{/ each }}
```

where I would attach a category inside the pages registration.

**Comment by timfam** [comment]
yes that should pass the right context to each

**Comment by rwatts3** [comment]
ok I just figured it out too. So everything within the pages entity is registered as a helper. So if I did a select dropdown of Navigation items or parents, I can pass nav="Main" and any pages within the main navigation will render.

**Comment by rwatts3** [comment]
@timfam 
DId you ever figure out how to add tabular to the homepage with orion entities ?

**Comment by timfam** [comment]
Sorry buddy I'm planning on dealing with that issue this weekend if I can.
