### ISSUE TITLE
Integrate alanning:meteor-roles for permissions and roles

### ISSUE THREAD

**Issue by mraak** [orionjs/orion#85]
Since this was mentioned so many times in various places maybe it's best to have its own ticket. At least we can better track the progress this way.

https://github.com/alanning/meteor-roles

**Comment by timfam** [comment]
@mraak reference the other tickets here and we will try to avoid duplicate tickets and discuss roles here for now

**Comment by mraak** [comment]
https://github.com/orionjs/orion/issues/68
Here's one, can't find the other one any more.

Any ETA on this?

**Comment by nicolaslopezj** [comment]
This will come with 1.0. Check the progress here #81
