### ISSUE TITLE
views for pages and files should go into bootstrap

### ISSUE THREAD

**Issue by kevohagan** [orionjs/orion#86]
Im not sure what the best way is for this , but i guess the views for pages and files should go into a separate package for easy overriding. 

Any thoughts on this?

**Comment by nicolaslopezj** [comment]
Package is not the same as repo. Packages did not change, you can still override only the bootstrap package

**Comment by kevohagan** [comment]
@nicolaslopezj but in the pages packages the views are defined there  ( adminPagesCreate, adminPagesDelete, etc etc ) if i override the bootstrap package it doesnt override these templates obviously, i cand overrride manually with template extension but it feels hacky.

Im sure there could be a better way for this no?

**Comment by timfam** [comment]
I think the two pf you are saying different things, @kevohagan was asking how to override templates

**Comment by timfam** [comment]
@kevohagan we fix this issue for entities but not pages.

**Comment by nicolaslopezj** [comment]
Oh, you can't override templates. What you can do is use the new app that @timfam made for custom templates or clone the bootstrap repo
