### ISSUE TITLE
is pages and relationships (and files) important to be outside of core?

### ISSUE THREAD

**Issue by kevohagan** [orionjs/orion#87]
This is a question.

I am wondering if there is much advantage of keeping pages and relationships outside of core ( same as files), i suppose most people will be using theses anyways? 

just starting a discussion here , see what people think :)

**Comment by nicolaslopezj** [comment]
In 1.0 everything will be in different packages - even entities - and orion:core will install the "default packages".
Pages its not always used, so I don't think it will be in that group. 
Relationships isn't either, but it isn't disruptive, Maybe it could be in that group

**Comment by timfam** [comment]
pages and Relationship should stay out until future needs warrants it. We should try to put as little into core as possible and like @nicolaslopezj core should just install a default set of packages

**Comment by kevohagan** [comment]
okay perfect! totally makes sense!
