### ISSUE TITLE
Question : Custom Admin link

### ISSUE THREAD

**Issue by rwatts3** [orionjs/orion#88]
I know someone mentioned hit it here before but I can't seem to find it in the issues. My question is regarding adding a custom option to the admin panel and rendering a custom template all inside of the admin area.

For example I want to add a option to view page view statistics.  
I am creating an extension package for this.  A sidebar item will be added called Statistics . I then want to render a template I will use to show the statistical data . But I want it to be inside the admin panel and look and feel just like the admin area.  
Any advice ?

**Comment by timfam** [comment]
Besides the doing the necessary permission, login checks, I think you just have to use the admin layout in the router. 
```
controller: orion.RouteController,
```
That should do it

**Comment by rwatts3** [comment]
Ok k will give this a shot.

**Comment by timfam** [comment]
There is also a list of templates that core validates login status for
``` 
Router.plugin('ensureSignedIn', {
	only: [
		'adminDictionaryUpdate',
		'adminUsersIndex',
		'adminUsersCreate',
		'adminUsersEdit',
		'adminUsersDelete',
		'adminConfigUpdate',
		'adminEntitiesIndex',
		'adminEntitiesCreate',
		'adminEntitiesUpdate',
		'adminEntitiesDelete'
	]
});
``` 
@nicolaslopezj we need to make this list extensible

**Comment by rwatts3** [comment]
Maybe a method in core and have the plugin loop through what's passed to the method as an array

**Comment by rwatts3** [comment]
I think a method may already exist I'll see what he says.

**Comment by timfam** [comment]
I don't there is a method yet, Controllers can be inherited by extending a parent
```
childController = ParentController.extend(options)
```
However method makes it easier for devs and centralizes a single controller we can improve

**Comment by kevohagan** [comment]
I think telescope does something similar

**Comment by rwatts3** [comment]
Can Orion Relationships be used to group the entities inside the sidebar. ? This would make relationships a dependency in corps I'm not sure if you want this or not.  But I'm finding it to be easier to build the entity groups using relationships extension.

**Comment by nicolaslopezj** [comment]
I don't know how could you do that right now, but in 1.0 you will have the possibility to override templates

**Comment by rwatts3** [comment]
Hmm , I think I will hold off on this update until .1.0 . 
In the meantime I will hop over to the 1.0 Issue and see what I can contribute to there.
