### ISSUE TITLE
Integrate meteor-reactive-css

### ISSUE THREAD

**Issue by timfam** [orionjs/orion#89]
What do you guys think of integrating https://github.com/ccorcos/meteor-reactive-css into Orion. 
here is a live demo http://reactive-css.meteor.com/  We can use dictionary to allow admin to make css changes and it is reactive
```
// set the css properties here
styles = new ReactiveDict()
styles.set('primary', 'blue')
styles.set('background', 'white')

// get the properties
css({
  '.page': {
    'backgroundColor': function() {
      return styles.get('primary');
    },
    'heightpx': function() {
      return styles.get('background');
    }
  }
});
```

@ccorcos is the maintainer and I think he will love orion
Your thoughts?

**Comment by ccorcos** [comment]
that would be a really awesome use of my package!

**Comment by nicolaslopezj** [comment]
Great!!! I made hacky things in other projects to achieve this.
I think this could be a orion attribute

**Comment by kevohagan** [comment]
i think that would make for a great orion plugin! the ability to override css on custom pages

**Comment by ccorcos** [comment]
Holy crap people:

http://tympanus.net/Development/InteractiveColoringConcept/

**Comment by timfam** [comment]
I say holy crap too, that is super awesome!!!

**Comment by kevohagan** [comment]
Yes i saw that yesterday! and thought straight of reactive-css!! :)
