### ISSUE TITLE
started work for markdown editor integration

### ISSUE THREAD

**Issue by kevohagan** [orionjs/orion#90]
So i think froala and summernote are great, but i have a custom template that has speciale styling for html tags and would like to be able to write posts in markdown.

I found this great package : https://atmospherejs.com/d4nyll/epic

and it would be a perfect candidate for a orionjs plugin.

started work here :
https://github.com/kevohagan/orion-epic

dont really know what im doing so any help apreciated ! :)

**Comment by nicolaslopezj** [comment]
Great!

**Comment by rwatts3** [comment]
Nice , I was just thinking the other day that we needed markdown editor.

**Comment by timfam** [comment]
@kevohagan I just took a look at the repo so far so good, I will take a closer look later. Good one

**Comment by kevohagan** [comment]
yeah just copy pasted the stuff from froala and summernote , this should be
easier since there is not file uploading throuhg the editor

**Comment by rwatts3** [comment]
hmm , I thought in makdown you could paste an image and trigger file upload similar to how github does ? 

It would be cool to do this in your package as well.

**Comment by kevohagan** [comment]
well i know you can put in a img url , dont know about drag and drop image
though .. http://epiceditor.com/

**Comment by kevohagan** [comment]
hey @nicolaslopezj @timfam @rwatts3 , just updated the package now seems to work fine!

let me know what you think! :)

**Comment by timfam** [comment]
Ok I will give a try soon, nice one!

**Comment by nicolaslopezj** [comment]
How is this going?

**Comment by timfam** [comment]
I think he is done, we just need it presented as tested package for v10. @kevohagan test and confirm it works with v1.0

**Comment by nicolaslopezj** [comment]
Ok, I wanted a markdown editor. I hope it can be released soon

**Comment by kevohagan** [comment]
hey guys! yes i havent touched it since i was waiting for 1.0 to get my
hands dirty. There shouldnt be any breaking changes i guess. Anyway it was
not totally finished, it needed a bit more work to be fully released.
ETA : a few days

Awesome job on 1.0 im sure@

**Comment by amejias101** [comment]
Does this mean that it was integrated in 1.0?

**Comment by rwatts3** [comment]
Alex ,
Does your editor have a split pane for seeing the preview in the right or
left column? See here for an example http://stackedit.io

**Comment by nicolaslopezj** [comment]
This was closed because it is an announcement, not an issue

**Comment by amejias101** [comment]
@rwatts3 Nope, is it supposed to?

**Comment by rwatts3** [comment]
Not that it's supposed to but it would be nice if it could . Think of
stackedit inside of a modal . Would this be too hard to implement ?

On Tuesday, May 19, 2015, Nicolás López <notifications@github.com> wrote:

> This was closed because it is an announcement, not an issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orionjs/orion/issues/90#issuecomment-103670063>.
>


-- 
Ryan Watts
E.ryandwatts@gmail.com
C.520-442-8962
F.520-437-0914
IN. https://www.linkedin.com/in/ryandwatts

**Comment by amejias101** [comment]
¯\_(ツ)_/¯  I was wondering if the work mentioned @kevohagan was implemented in version 1.0, I was not intending to write a package for it. Sorry for the confusion

**Comment by rwatts3** [comment]
Oh I see.

On Tuesday, May 19, 2015, Alex Mejias <notifications@github.com> wrote:

> ¯_(ツ)_/¯ I was wondering if the work mentioned @kevohagan
> <https://github.com/kevohagan> was implemented in version 1.0, I was not
> intending to write a package for it. Sorry for the confusion
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orionjs/orion/issues/90#issuecomment-103671383>.
>


-- 
Ryan Watts
E.ryandwatts@gmail.com
C.520-442-8962
F.520-437-0914
IN. https://www.linkedin.com/in/ryandwatts
