### ISSUE TITLE
Theme Support

### ISSUE THREAD

**Issue by rwatts3** [orionjs/orion#91]
I was just looking at the Ghost platform , not too long ago to try and get some ideas for areas where we can add features. Something I noticed that a lot of people in the community like is the ability to drop in a theme. We should try to find a way to build themes for Orion. Where we could even create a theme marketplace where users can select themes built by the community then drop it into their Orion app and move along. 

One thing I did notice out of the back is that meter uploads everything. I wonder if there is a way we can ommit certain directories from getting pushed live until we explicitly tell it to. For instance this is where the user would select the theme available in the admin area then that directory will be used instead of the previous themes directory and all other directories under theme would be omitted. 

Again these are just thoughts i'd be happy to know your ideas. 
@nicolaslopezj @timfam

**Comment by rwatts3** [comment]
On another note I suppose we could build an api and guide for building apps such as the example-blog then build it into a package. Therefore if the package is added then the theme will be loaded automatically.

**Comment by nicolaslopezj** [comment]
Thats a good idea, we need to figure out how to add templates dynamically

**Comment by rwatts3** [comment]
Yeah maybe passing a theme id , or passing a theme name would allow it to pull everything from that folder as a theme. This could be something for the future, I think with 1.0 and 1.0 api this could easily be implemented at a later time.

**Comment by rwatts3** [comment]
BTW I like how the updates to `1.0` will completely leave `Ghost` cms in the dust.

**Comment by vonwao** [comment]
@rwatts3  yes, but I thought the whole point of ghost is that they don't want to be a CMS, just a blogging platform.  What I like about Orion is that it has the potential to create sophisticated, rich apps.  It's kind of like Rails but simpler.  

I do like the idea of "drop in" theme support.  And how about other Wordpress style plugins?  I think a big problem with Wordpress is all the fragmentation in the area of themes.  You have to choose from like 10 different "theme frameworks", each one has their own custom admin panels, and "website builders" etc.  Maybe Orion can improve on this situation!

**Comment by timfam** [comment]
right on the money. I promise you orion will not be messy

**Comment by rwatts3** [comment]
@vonwao 
You are correct. There are a lot of features about Ghost that I simply do not like. Which is why I appreciate Orion as much as I do. With that being said my biggest point , is that drop in themes would be really cool. But in a way we already do this with Orion. 

With the new Orioni Site that @nicolaslopezj is building , the api for the new site and the example blog will provide a template for users to start with and build their own site/app. By cloning the example blog it has great documentation, and a great starter. What I would like to help improve and i'm sure @timfam can agree is more strict documentation on folder structure , and when/where to put your files. This way people can clone the example blog build their own theme, and we can even include a `built with orion` or theme marketplace where people can provide themes they've built that follow the Orion  structure. 

For example , in my apps that I have made, I usually put the "theme" or "app" inside a folder called app, then define my client/server specific folders within that root. And I create a second root called "orion" , and put my orion specific code inside of that. 

Essentially a user could make their "app" folder a package or a simple repository , and other users can clone their repository. 

Now here is what I was thinking in terms of theming. What if we could tell meteor to ignore everything inside of app , and only pay attention to files in app2 . Where app would be someTheme , and app2 would be someOtherTheme. Then inside of Orion admin select someTheme, and meteor will use someTheme to render the front end ignoring all files in someOtherTheme. And once they switch back it will ignore someTheme , and only use files in someTheme2. 

Folder structure could be something like this. 

- app
 - themes
   - someTheme 
    - someOtherTheme
- orion

**Comment by timfam** [comment]
@rwatts3 That theme structure is the end goal, It should be possible to use two separate themes for an app, an Admin and a front-end. Admin is heavy, so it should restricted to admin/*.

**Comment by rwatts3** [comment]
Alright, I suppose I should wait for 1.0 it seems like all of these thoughts are already being built.

**Comment by timfam** [comment]
Themes are now supported closing issue
