### ISSUE TITLE
Removing pages from url

### ISSUE THREAD

**Issue by rwatts3** [orionjs/orion#93]
i believe there was an issue created for this before.  Do we have a solution or starting point for removing pages from the url ?

**Comment by timfam** [comment]
Pages can't be removed just yet but I think it not overly complex to do. I will look into it shortly, I may habe the answer. 
Btw and off topic I have been working on grouping menus for both admin and front end.

**Comment by rwatts3** [comment]
Thank you I will stand by to see your solution.  Also the grouping menus sounds good.  What is your thought process on the grouping ?

**Comment by timfam** [comment]
I fixed this and it now uses the name of the template .ie contact/one, faq/pageone
I using redirect for this and you just have to create simple routes 
```
Router.route('/contact/:url',  { 
	name: 'pages',
	controller: orion.PagesController,
});
Router.route('/faq/:url',  { 
	name: 'pages',
	controller: orion.PagesController,
});
```
I will do a PR later but I do like to see If I can make a generator for this routes. So if you are not in rush, I will try and play around this tonight. The solution is still a bit hacky but can be cleaned up later

**Comment by rwatts3** [comment]
Nice job man can you paste in the link to the branch you are working on.  Tonight I too will jump in and try to work on the generator.

**Comment by rwatts3** [comment]
Btw I use google hangouts so if you ever want to collaborate just shoot me an im

**Comment by timfam** [comment]
Great! I did it on local, will fork and push later.

**Comment by nicolaslopezj** [comment]
I think that registering the routes after all the other works, I haven't tested but maybe doing this could work:

```js
Meteor.startup(function () {
  Router.route('/:url', function() {
    ...
  }, { name: 'pages' });
});
```

If this works, it will come with 1.0 #81

**Comment by timfam** [comment]
Yes that works, no need for a generator and @nicolaslopezj can you simply remove 
```
/pages
``` and push the update I don't need to do a PR for this. thanks for saving me from making a generator :)

**Comment by timfam** [comment]
https://github.com/orionjs/orion/blob/master/pages/lib/routes.js line 39

**Comment by rwatts3** [comment]
Has the update been pushed yet ?
