### ISSUE TITLE
Create non-restricted entity forms

### ISSUE THREAD

**Issue by ryanbuiltthat** [orionjs/orion#94]
Is it possible to create a form to insert an entity from a non-loggedin user? Seems simple but I'm having a helluva time getting it to sync up with autoform.

**Comment by timfam** [comment]
Entities have permission check, I think the best way to achieve this is have a permission/role called guest and allow guest to post that entity. I can look into this and discuss with Nick, can you share your use case  for this requirement?

**Comment by ryanbuiltthat** [comment]
So I have a single page app that's a marketing tool for a service company.
When a rep from the company logs in, they're able to select a few items
from the page, and send a receipt of the selection to a customer. I want to
also have that write to the db which is managed via admins in orion. I've
been working on an extended orion-core but was hoping for a quick way for
this. Essentially if there were backwards compatability with regular
collections it'd be fine no sweat. But if I define a collection the regular
way I'm not sure then how to use it in the admin. I can send you the URL if
you wish so you could see a live example.

**Comment by ryanbuiltthat** [comment]
Another use-case would be a simple contact form. Email isn't 100% reliable either because of user issues or system issues....so it seems a pretty standard thing to have a contact form also keep a record of the submission that could be re-sent, tracked, etc......I don't want all those features added, I just want a way to relate a "public" facing form to the admin.

**Comment by timfam** [comment]
I get it. I have not used orion for contact form I used autoform directly but now that you bring this up, I do like to make it work. I can take a look at it tomorrow, it should be doable without breaking the banks :).

**Comment by ryanbuiltthat** [comment]
Thanks tim. This was supposed to be a super simple page. But I added a tiny little animated svg check box (from codrops) and when the client saw that they said "hey let's make it so our sales reps can 'check' off items in front of the customer on their ipads and send them their receipt". because yea that is a good use of time...

regardless. I'm working on having the receipts submitted go into the DB so the sales manager can track them. 
And I just realized something. The sales reps, the ones who will send the receipts will be users! Wow I need sleep. So I guess what I can't figure out is how to break off an autoform to use outside the admin view? When I try to and map it to the entity I have created, it doesn't recognize the schema. My bad. But after I wrote the OP it does seem like some handy functionality to have anyways :P

**Comment by timfam** [comment]
Get some sleep, it helps I will see what i can do

**Comment by nicolaslopezj** [comment]
Hi @ryanbuiltthat, 
A simple solution for this is to the Meteor.methods

```html
{{> quickForm schema='orion.entities.yourentity.schema' id="myForm" type="method" meteormethod="insertMethod" }}
```

```js
Meteor.methods({
  insertMethod: function (doc) {
    check(doc, orion.entities.yourentity.schema);
    return orion.entities.yourentity.collection.insert(doc);
  }
});
```

**Comment by timfam** [comment]
Still have to create an entity to view the results securely in admin. He
does not want to bypass db completely like in a simple contact form

**Comment by nicolaslopezj** [comment]
"```yourentity```" would be the entity in this case

**Comment by ryanbuiltthat** [comment]
Ahh the orion schema naming is where I was stuck. I had the autoform but it
didn't like any of the hackery I was doing and kept telling me I needed to
define a schema.

The permission model works well out of the box for this project as I want
admins to see all but only want users to see entities they've created.

Taking what was supposed to be a WordPress site and turning it into a
hyper-light web app is an amazing feeling!

**Comment by timfam** [comment]
Sorry I spoke too soon. The code is referencing an existing entity. That
needs to go into the entity tutorial.

**Comment by timfam** [comment]
Just added that to the tutorial

**Comment by ryanbuiltthat** [comment]
In your tutorial you mention creating a js file for the quickform. Am I correct in that that is where the quickform handlebars should go? In the js file?

**Comment by ryanbuiltthat** [comment]
Had to make a few adjustments in order to get this tutorial to work...using contacts as the collection here:

- Added two new templates in the `client/view/contacts` folder.
- `guestContact.html` & `updateContact.html`
- added a js file to the `view/contacts` folder with this line:
`Template.registerHelper("guestReceiptsCreate", orion.entities.contacts)`
- Subscribed to contacts in my home route (not sure if that's needed???)
- modified the quickform call to reference the collection and not the schema:
`{{> quickForm collection='orion.entities.contacts.collection' id="myForm" type="method" meteormethod="insertMethod" }}`
- added individual checks for each field on the contact form. passing `doc` to check and comparing it to the schema resulted in a Match.error. When I outputted the doc and schema it seems that autform or orion (haven't figured out which yet) wasn't passing the field type? The error in the server console was telling me that `fullName` was send as a String but that it was expecting an Object. Based on what the schema output shows, that makes sense I just can't figure out why. Below is the output of both doc and schema.

## Output of doc

      {
        "fullName":"evervreg",
        "phone":"erve",
        "email":"ewfe"
      }
## Output of orion.entities.contacts.shema

      {
        "createdAt":
        {
          "autoform":
          {
            "omit":true
          }
        },
        "updatedAt":
          {
            "autoform":
            {
              "omit":true
            },
            "denyInsert":true,
            "optional":true
          },
          "createdBy":{
            "autoform":{
              "omit":true
            },
            "optional":true
          },
          "fullName":{
            "label":"Full Name"
          },
          "phone":{
            "optional":true,
            "label":"Phone"
          },
          "email":{
            "optional":true,
            "label":"Email"
          },
          "comment":{
            "optional":true,
            "label":"Comment"
          }
        }

**Comment by ryanbuiltthat** [comment]
Had to make a few adjustments in order to get this tutorial to work...using contacts as the collection here:

* Added two new templates in the `client/view/contacts` folder.
    * `guestContactCreate.html` & `guestContactUpdateDefault.html`
* added a js file to the `view/contacts` folder with this line:
    * `Template.registerHelper("guestContactCreate", orion.entities.contacts)`
* Subscribed to contacts in my home route __(not sure if that's needed???)__
* Modified the quickform call to reference the collection and not the schema:
    * `{{> quickForm collection='orion.entities.contacts.collection' id="myForm" type="method" meteormethod="insertMethod" }}`
    * When the quickForm was set with the schema attribute I couldn't get passed the following error which prevented the quickForm from even displaying:
```
    Exception in template helper: TypeError: undefined is not a function
        at Object.autoFormFieldNames (http://localhost:3000/packages/aldeed_autoform.js?e71f561d26e90711b8a4ddf6136073fdffff296d:1426:20)
        at bindDataContext (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2880:16)
        at Blaze._wrapCatchingExceptions (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1651:16)
        at http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2928:66
        at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3476:12)
        at wrapHelper (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2927:27)
        at Spacebars.call (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:172:18)
        at Spacebars.mustacheImpl (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:109:25)
        at Object.Spacebars.dataMustache (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:141:39)
        at http://localhost:3000/packages/aldeed_autoform.js?e71f561d26e90711b8a4ddf6136073fdffff296d:7323:22
```
* Added individual checks for each field on the contact form. passing `doc` to check and comparing it to the schema resulted in a Match.error. When I outputted the doc and schema it seems that autform or orion (haven't figured out which yet) wasn't passing the field type? The error in the server console was telling me that `fullName` was send as a String but that it was expecting an Object. Based on what the schema output shows, that makes sense I just can't figure out why. Below is the output of both doc and schema.

### Output of doc
```
      {
        "fullName":"evervreg",
        "phone":"erve",
        "email":"ewfe"
      }
```
### Output of orion.entities.contacts.shema
```
      {
        "createdAt":
        {
          "autoform":
          {
            "omit":true
          }
        },
        "updatedAt":
          {
            "autoform":
            {
              "omit":true
            },
            "denyInsert":true,
            "optional":true
          },
          "createdBy":{
            "autoform":{
              "omit":true
            },
            "optional":true
          },
          "fullName":{
            "label":"Full Name"
          },
          "phone":{
            "optional":true,
            "label":"Phone"
          },
          "email":{
            "optional":true,
            "label":"Email"
          },
          "comment":{
            "optional":true,
            "label":"Comment"
          }
        }
```
Also I did modify the entity object a bit but it doesn't seem to make a difference. Originally I tried to create the SimpleSchema in the entity definition which clearly that didn't work since orion is taking care of that. But I kept the schema out of the entity definition anyways to see if possibly it was a formatting issue which caused the check to fail.

 ### Modified entity definition 
 >orion/entities/contacts.js

```
    Schemas = {};
    Schemas.Contact = {
      fullName: {
        type: String,
        label: "Full Name"
      },
       phone:{
        type: String,
        optional: true,
        label: "Phone",
      },
      email:{
        type: String,
        optional: true,
        label: "Email",
      },
      comment:{
        type: Number,
        optional: true,
        label: "Comment",
      },
    };
    orion.addEntity('contacts', Schemas.Contact, {
      icon: 'bookmark',
      sidebarName: 'Contacts',
      pluralName: 'Contacts',
      singularName: 'Contact',
      //Optional - Only if your need to override the generic template
      createTemplate:'guestContactCreate',
      updateTemplate:'guestContactUpdateDefault',
      tableColumns: [
          { data:'fullname', title: 'Full Name' },
      ]
    });
```

**Comment by timfam** [comment]
Thanks for the detailed feedback, yesterday was a long day and I tutorials
always have room for improvements so I will update as soon as you have it
working. I should setup a local instance and try getting it to work. This
is very important contribs if orion I'd to support surveys out of the box

**Comment by rwatts3** [comment]
@timfam. I have nitrous.io and IntelliJ.  At my office our developers collaborate on IntelliJ by adding each other.  And we can see specific points in code.  If you don't have IntelliJ nitrous.io allows the same collaboration.  It would be cool if we could use this to work together on solutions and help the community in questions like  this.  

Let me know your thoughts

**Comment by ryanbuiltthat** [comment]
What is really awesome is I have not only this working, but my whole project is almost complete. I'm just adding bells and whistles like PDF export of a doc, letting a user customize various aspects of their UI, etc. I really am impressed with orion, I still have a need to decouple the back from the front but that's on the schedule for monday! 

I think what could be of great benefit is a detailed document on the api with all the endpoints. I can help with that as I work through some of it.

After this weekend my next challenge with orion is to create an administrative ui. I have it started off of a fork and if it comes together will share it out. Again, it's only possible because of how flexible this framework is which is just fantastic!

**Comment by rwatts3** [comment]
@nicolaslopezj 
Is currently working on v1.0 where the admin area will be built into a simple-theme , He will provide documentation on how to build any admin layout you want. This is probably one of the most beneficial things that you can use , so if you can hold off until 1.0 you will be able to build the admin area any way you'd like.

**Comment by ryanbuiltthat** [comment]
Music to my ears!!!

**Comment by timfam** [comment]
Yes good idea to wait.

**Comment by timfam** [comment]
We setup etherpad at orionjs.org for collaboration we will soon add it to
the docs.

**Comment by rwatts3** [comment]
Nice work @timfam
