### ISSUE TITLE
How to get the current user. 

### ISSUE THREAD

**Issue by rwatts3** [orionjs/orion#95]
What is the best way to get the current logged in users name. 
I am currently exploring `orion.users` but I can't find where to grab the current users name.

**Comment by nicolaslopezj** [comment]
The name is in ```profile.name```

**Comment by rwatts3** [comment]
So would this be `orion.users.profile.name` ?

**Comment by nicolaslopezj** [comment]
Like this 
```js
Meteor.user().profile.name
```

**Comment by rwatts3** [comment]
Ah I see , 

Thanks for looking into that.
