### ISSUE TITLE
Created Project to Provide Native Cordova Integration

### ISSUE THREAD

**Issue by rwatts3** [orionjs/orion#96]
I am working on a project to provide native cordova notifications to Orion.
For instance the first integration is Cordova Native Notifications. The user will define an entity called `notifications` . When they create a new notification they will be able to send Android / IOS notifications directly to the device from their app. 

This repository is just the start of many of the Cordova items I will try to build so that they can be controlled from the admin panel. 

Let me know your thoughts. 

Also there is a new name space called `orion.cordova` , and each integration will follow this namespace so `orion.cordova.notifications` all the methods integrated for notifications will follow this namespace. 

http://github.com/rwatts3/orionjs-cordova

**Comment by nicolaslopezj** [comment]
@rwatts3 that's awesome!

**Comment by timfam** [comment]
Super awesome!

**Comment by kevohagan** [comment]
That seem great! :)
